### ISSUE TITLE
Website: error boxes get misaligned when scrolling

### ISSUE THREAD

**Issue by strager** [quick-lint/quick-lint-js#1010]
![image](https://github.com/quick-lint/quick-lint-js/assets/48666/4d4b6c23-4e97-4b15-abd6-e2194477501b)

Firefox on Windows

**Comment by lrbn86** [comment]
Looked into this [commit](https://github.com/quick-lint/quick-lint-js/commit/9fafaa963a22d05f6ed9e833ccaf4dc131723a9f) for potential margin/padding issue.

Two potential solutions:

1. Remove entire [code-input-marks rule](https://github.com/quick-lint/quick-lint-js/commit/9fafaa963a22d05f6ed9e833ccaf4dc131723a9f#diff-944ae6e9bb40892869596709fb478eb07821688b56c6930d33d2e033f3615125R33-R36)

https://github.com/quick-lint/quick-lint-js/assets/12689519/eec1df28-61f9-4ea9-94aa-883b87a65cf9

<br>
<br>

2. Replace padding to be at least 10px from 0 on [code-input-marks-scroller rule](https://github.com/quick-lint/quick-lint-js/commit/9fafaa963a22d05f6ed9e833ccaf4dc131723a9f#diff-944ae6e9bb40892869596709fb478eb07821688b56c6930d33d2e033f3615125R51)

https://github.com/quick-lint/quick-lint-js/assets/12689519/2c3c9f59-c819-428c-9f18-e8c75039b5f8

**Comment by strager** [comment]
> Replace padding to be at least 10px from 0 on [code-input-marks-scroller rule](https://github.com/quick-lint/quick-lint-js/commit/9fafaa963a22d05f6ed9e833ccaf4dc131723a9f#diff-944ae6e9bb40892869596709fb478eb07821688b56c6930d33d2e033f3615125R51)

This workaround lead me to the real problem: We were sizing the scroller based on the code input's offsetHeight (which includes scroll bars) instead of its clientHeight (which excludes scroll bars). The browser's scroll bars on Firefox Windows made caused our scroller to be too big. Shrinking it by ~20px (which your padding workaround did) made it work. But I landed a proper fix: b28c87e6f2d978858298ee121cde2da023ef9abf

Thanks for your help, @lrbn86.
