### ISSUE TITLE
6$: error on `${}` (missing expression)

### ISSUE THREAD

**Issue by strager** [quick-lint/quick-lint-js#1013]

**Comment by maxweilun1989** [comment]
@strager  I'd like to give it a try, Could you please assign it to me.

**Comment by strager** [comment]
@maxweilun1989 Sure. Let me know if you need any help.

**Comment by maxweilun1989** [comment]
@strager HI, want to make it clear. Should this error only triggered when `${}` is inside a template string?.

**Comment by strager** [comment]
@maxweilun1989 Yes.

**Comment by HicaroD** [comment]
It's been two months since. Can I give it a try? I have an idea on how to solve it.

**Comment by HicaroD** [comment]
I actually already solved it. I can make a PR.
