### ISSUE TITLE
8$: error on '...' as expression

### ISSUE THREAD

**Issue by strager** [quick-lint/quick-lint-js#1023]
```javascript
        func.codeSegmentIndex = ...;
        func.codeOffset = ...;
        func.codeSize = ...;
```
quick-lint-js does not diagnose the above, but it should.

**Comment by UditJarwal** [comment]
@strager also tell me more about this issue. Till now I have figured out that I have to create a new diagnost

**Comment by jaitjacob** [comment]
@UditJarwal here is some info I hope helps you out with your first contribution. To understand what diagnostic you have to implement you could try running the code in TypeScript & ESLint Playground. They normally give me a sense of what is the error/non-compliance with the language standard. 

In your case, you can see what errors show up,
1. [TypeScript Playground](https://www.typescriptlang.org/play?#code/GYVwdgxgdBD2AmBTAyog5gW0WALgSTCQA8ACAXhKioG4AoUSGBRAeWGAGdEdzKb7w0OEmQBLAF6JeVKNSA)
2. [ESLint Playground](https://eslint.org/play/#eyJ0ZXh0IjoiZnVuYy5jb2RlU2VnbWVudEluZGV4ID0gLi4uO1xuZnVuYy5jb2RlT2Zmc2V0ID0gLi4uO1xuZnVuYy5jb2RlU2l6ZSA9IC4uLjsiLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOiJsYXRlc3QiLCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7ImNvbnN0cnVjdG9yLXN1cGVyIjpbImVycm9yIl0sImZvci1kaXJlY3Rpb24iOlsiZXJyb3IiXSwiZ2V0dGVyLXJldHVybiI6WyJlcnJvciJdLCJuby1hc3luYy1wcm9taXNlLWV4ZWN1dG9yIjpbImVycm9yIl0sIm5vLWNhc2UtZGVjbGFyYXRpb25zIjpbImVycm9yIl0sIm5vLWNsYXNzLWFzc2lnbiI6WyJlcnJvciJdLCJuby1jb21wYXJlLW5lZy16ZXJvIjpbImVycm9yIl0sIm5vLWNvbmQtYXNzaWduIjpbImVycm9yIl0sIm5vLWNvbnN0LWFzc2lnbiI6WyJlcnJvciJdLCJuby1jb25zdGFudC1jb25kaXRpb24iOlsiZXJyb3IiXSwibm8tY29udHJvbC1yZWdleCI6WyJlcnJvciJdLCJuby1kZWJ1Z2dlciI6WyJlcnJvciJdLCJuby1kZWxldGUtdmFyIjpbImVycm9yIl0sIm5vLWR1cGUtYXJncyI6WyJlcnJvciJdLCJuby1kdXBlLWNsYXNzLW1lbWJlcnMiOlsiZXJyb3IiXSwibm8tZHVwZS1lbHNlLWlmIjpbImVycm9yIl0sIm5vLWR1cGUta2V5cyI6WyJlcnJvciJdLCJuby1kdXBsaWNhdGUtY2FzZSI6WyJlcnJvciJdLCJuby1lbXB0eSI6WyJlcnJvciJdLCJuby1lbXB0eS1jaGFyYWN0ZXItY2xhc3MiOlsiZXJyb3IiXSwibm8tZW1wdHktcGF0dGVybiI6WyJlcnJvciJdLCJuby1leC1hc3NpZ24iOlsiZXJyb3IiXSwibm8tZXh0cmEtYm9vbGVhbi1jYXN0IjpbImVycm9yIl0sIm5vLWV4dHJhLXNlbWkiOlsiZXJyb3IiXSwibm8tZmFsbHRocm91Z2giOlsiZXJyb3IiXSwibm8tZnVuYy1hc3NpZ24iOlsiZXJyb3IiXSwibm8tZ2xvYmFsLWFzc2lnbiI6WyJlcnJvciJdLCJuby1pbXBvcnQtYXNzaWduIjpbImVycm9yIl0sIm5vLWlubmVyLWRlY2xhcmF0aW9ucyI6WyJlcnJvciJdLCJuby1pbnZhbGlkLXJlZ2V4cCI6WyJlcnJvciJdLCJuby1pcnJlZ3VsYXItd2hpdGVzcGFjZSI6WyJlcnJvciJdLCJuby1sb3NzLW9mLXByZWNpc2lvbiI6WyJlcnJvciJdLCJuby1taXNsZWFkaW5nLWNoYXJhY3Rlci1jbGFzcyI6WyJlcnJvciJdLCJuby1taXhlZC1zcGFjZXMtYW5kLXRhYnMiOlsiZXJyb3IiXSwibm8tbmV3LXN5bWJvbCI6WyJlcnJvciJdLCJuby1ub25vY3RhbC1kZWNpbWFsLWVzY2FwZSI6WyJlcnJvciJdLCJuby1vYmotY2FsbHMiOlsiZXJyb3IiXSwibm8tb2N0YWwiOlsiZXJyb3IiXSwibm8tcHJvdG90eXBlLWJ1aWx0aW5zIjpbImVycm9yIl0sIm5vLXJlZGVjbGFyZSI6WyJlcnJvciJdLCJuby1yZWdleC1zcGFjZXMiOlsiZXJyb3IiXSwibm8tc2VsZi1hc3NpZ24iOlsiZXJyb3IiXSwibm8tc2V0dGVyLXJldHVybiI6WyJlcnJvciJdLCJuby1zaGFkb3ctcmVzdHJpY3RlZC1uYW1lcyI6WyJlcnJvciJdLCJuby1zcGFyc2UtYXJyYXlzIjpbImVycm9yIl0sIm5vLXRoaXMtYmVmb3JlLXN1cGVyIjpbImVycm9yIl0sIm5vLXVuZGVmIjpbImVycm9yIl0sIm5vLXVuZXhwZWN0ZWQtbXVsdGlsaW5lIjpbImVycm9yIl0sIm5vLXVucmVhY2hhYmxlIjpbImVycm9yIl0sIm5vLXVuc2FmZS1maW5hbGx5IjpbImVycm9yIl0sIm5vLXVuc2FmZS1uZWdhdGlvbiI6WyJlcnJvciJdLCJuby11bnNhZmUtb3B0aW9uYWwtY2hhaW5pbmciOlsiZXJyb3IiXSwibm8tdW51c2VkLWxhYmVscyI6WyJlcnJvciJdLCJuby11bnVzZWQtdmFycyI6WyJlcnJvciJdLCJuby11c2VsZXNzLWJhY2tyZWZlcmVuY2UiOlsiZXJyb3IiXSwibm8tdXNlbGVzcy1jYXRjaCI6WyJlcnJvciJdLCJuby11c2VsZXNzLWVzY2FwZSI6WyJlcnJvciJdLCJuby13aXRoIjpbImVycm9yIl0sInJlcXVpcmUteWllbGQiOlsiZXJyb3IiXSwidXNlLWlzbmFuIjpbImVycm9yIl0sInZhbGlkLXR5cGVvZiI6WyJlcnJvciJdfSwiZW52Ijp7ImVzNiI6dHJ1ZX19fQ==)

**Comment by strager** [comment]
> @strager also tell me more about this issue.

In JavaScript, `...` is a prefix operator. It is allowed in certain expression contexts. For example:
```javascript
let arrayCopy = [...array];
let f = (...args) => { console.log(args); };
```

There are two problems with the code which prompted this issue:
1. There is nothing after `...`.
2. Even if something was after `...`, an `...` expression isn't allowed here.

I envision the erroneous code should report something like "unexpected '...'; expected expression". (It'd be similar to [E0054 (diag_unexpected_token)](https://quick-lint-js.com/errors/E0054/), but slightly more helpful in its wording.)
```javascript
        func.codeSegmentIndex = ...;
                                ^^^  unexpected '...'; expected expression
        func.codeOffset = ...;
                          ^^^  unexpected '...'; expected expression
        func.codeSize = ...;
                        ^^^  unexpected '...'; expected expression
```

**Comment by UditJarwal** [comment]
@strager I understood the task now assign me the task and i will do the it.

**Comment by strager** [comment]
Oops, I thought I assigned it already. =X

**Comment by UditJarwal** [comment]
is there any preference in name which you want to give to this error

**Comment by UditJarwal** [comment]
@strager I am able to resolve what to do can please tell me steps to do this

**Comment by strager** [comment]
> is there any preference in name which you want to give to this error

No.

> @strager I am not able to resolve what to do can you please tell me steps to do this

1. Create a diagnostic type. https://quick-lint-js.com/contribute/create-diagnostic/
2. Write a test case in `test/test-parse-expression.cpp`. This will help you see what the AST currently is for the offending code, and that will give you a hint how to solve the problem. The `--gtest_filter=` command-line option might come in handy.
3. Find the relevant code in `src/quick-lint-js/fe/parse-expression.cpp` and add `printf`s/`cout<<`s or step through it in a debugger. Report the diagnostic and see if your test passes.

**Comment by strager** [comment]
@UditJarwal Are you still working on this task?

**Comment by isaacnonato** [comment]
Apparently the forner assignee is not working on the task anymore, can I be assigned? I came up with a solution for the issue.
