### ISSUE TITLE
10$: improve Vim install instructions on website

### ISSUE THREAD

**Issue by strager** [quick-lint/quick-lint-js#1026]
People get confused by our Vim install instructions, particularly the plugin-manager-specific parts. https://quick-lint-js.com/install/vim/winget/

Idea: make a tabbed interface so it's clear that each plugin manager instructions are mutually exclusive.

**Comment by Menotdan** [comment]
I claim this for-hire task. I expect payment after I complete this task. I will email the quick-lint-js team if I am assigned this task.
Just to be clear, this change is supposed to applied across all instruction sets (winget/nix/etc) that involve installing it as a Vim package in the user's preferred vim package manager, correct? Or is there a bigger/smaller scope for this issue?
I notice several install instructions under install/vim, such as debian, don't have instructions for specific vim package managers.

**Comment by strager** [comment]
> this change is supposed to applied across all instruction sets (winget/nix/etc) that involve installing it as a Vim package in the user's preferred vim package manager

Correct.

> I notice several install instructions under install/vim, such as debian, don't have instructions for specific vim package managers.

For Debian, the assumption is that you are using Debian's Vim which automatically runs Debian's Vim plugin manager. Installing the `quick-lint-js-vim` Debian package installs the quick-lint-js Vim plugin using Debian's Vim plugin manager, so no extra work is needed by the user.

**Comment by Menotdan** [comment]
> For Debian, the assumption is that you are using Debian's Vim which automatically runs Debian's Vim plugin manager. Installing the `quick-lint-js-vim` Debian package installs the quick-lint-js Vim plugin using Debian's Vim plugin manager, so no extra work is needed by the user.

Makes sense, thanks for clarifying.
Also further research after my initial post yields information that it is very very simple to add the tabbed interface to all the pages at once, because of the way the project is structured.
