### ISSUE TITLE
Website: drop HTTP/2.0 push

### ISSUE THREAD

**Issue by strager** [quick-lint/quick-lint-js#1027]
It looks like [Chromium doesn't support HTTP/2.0 push anymore](https://developer.chrome.com/blog/removing-push/). We should configure out server to stop using it if it has negative effects.

**Comment by k1ng440** [comment]
I will take this task and I will replace push with early hints if needed.

**Comment by strager** [comment]
I finixhed this task already in commit 75cfd74d016ce26aea7873835e91ea94c13e15db.

I don't think early hints are appropriate. They require a round trip and the browser's preloader will make the necessary requests anyway.
