### ISSUE TITLE
27$: emacs plugin

### ISSUE THREAD

**Issue by strager** [quick-lint/quick-lint-js#104]

**Comment by strager** [comment]
[Flycheck](https://www.flycheck.org/en/latest/) and [lsp-mode](https://emacs-lsp.github.io/lsp-mode/) look like good integration points.

We should probably recruit an emacs veteran to help with this task.

**Comment by wgrr** [comment]
I claim this for-hire task. I expect payment after I complete this task. I will email the quick-lint-js team if I am assigned this task.

**Comment by strager** [comment]
I think the Emacs plugin is basically implemented. Other tasks, such as #275 and #398, cover specific issues.
