### ISSUE TITLE
Update nvim-lspconfig's default config

### ISSUE THREAD

**Issue by k1ng440** [quick-lint/quick-lint-js#1047]
Hi,
I wanted to bring to your attention that the [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig) currently has a configuration for quick-lint-js for javascript filetype only ([config](https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/server_configurations/quick_lint_js.lua#L6C5-L6C14)). I think it would be beneficial to create a pull request and include typescript support as well.

**Comment by strager** [comment]
TypeScript support is still experimental, thus opt-in. Here's the documentation for using quick-lint-js TypeScript support with nvim-lspconfig:

https://github.com/quick-lint/quick-lint-js/blob/56b07155b54db76825b6bc0c6b6c8c4f3b31a740/plugin/vim/quick-lint-js.vim/doc/quick-lint-js.txt#L239-L249
