### ISSUE TITLE
docs(plugin/vscode): dead link in BUILDING.md

### ISSUE THREAD

**Issue by HicaroD** [quick-lint/quick-lint-js#1053]
In [Building](https://github.com/quick-lint/quick-lint-js/blob/master/plugin/vscode/BUILDING.md) section of [BULDING.md](https://github.com/quick-lint/quick-lint-js/blob/master/plugin/vscode/BUILDING.md), the link to the instructions to configure quick-lint-js with CMake is dead.

**Comment by strager** [comment]
Fixed in commit 82c22cbbbf515b2345f65d6cb90c57ae36400c3f.
