### ISSUE TITLE
8$: error on 'if(c);' in TypeScript mode

### ISSUE THREAD

**Issue by strager** [quick-lint/quick-lint-js#1067]
TypeScript does not allow `;` as the body of an `if` statement (and possibly other statements like `else` and `while`.

**Comment by samir-hamud** [comment]
hopelessdev from twitch here. I asked some questions about this issue on your stream yesterday.

I want to give this issue a try. Won't accept payment.

**Comment by samir-hamud** [comment]
Checking on typescriptlang, ts just doesnt allow the if statement. Else and while are allowed. Tested on all ts versions.
 
![image](https://github.com/quick-lint/quick-lint-js/assets/91815230/879457bd-ee4c-4bb7-bc23-b9df346ff242)

**Comment by strager** [comment]
> Else and while are allowed.

Oh, that's strange. Thanks for checking!
