### ISSUE TITLE
Tests failing on s390x on Alpine Linux

### ISSUE THREAD

**Issue by chereskata** [quick-lint/quick-lint-js#1078]
Hi,

after trying to package your cool linter for `Alpine Linux`, i noticed, that the following four tests failed on `s390x` architecture:

```
 PASSED  ] 2340 tests.
[  FAILED  ] 4 tests, listed below:
[  FAILED  ] Test_Trace_Reader_Writer.event_vscode_document_opened
[  FAILED  ] Test_Trace_Reader_Writer.event_vscode_document_closed
[  FAILED  ] Test_Trace_Reader_Writer.event_vscode_document_changed
[  FAILED  ] Test_Trace_Reader_Writer.event_vscode_document_sync
```

The whole build log is attached.

Thanks a lot!
[log.txt](https://github.com/quick-lint/quick-lint-js/files/12597257/log.txt)

**Comment by strager** [comment]
The title says "segfaulting", but I don't see evidence of a segfault in the logs. Did you mean that the test just failed?

Is s390x big endian? My hypothesis is that we just don't support big endian for trace file parsing. (Trace files are little endian.)

https://github.com/quick-lint/quick-lint-js/blob/77ffcea29507ba10b1f772e1be69766faf05b2d8/src/quick-lint-js/logging/trace-reader.cpp#L122

I created #1079 to address this issue, but I cannot test it.

**Comment by chereskata** [comment]
Thanks a log for your effort! I will ping you here once i have tested 
the patch.

The "segfault" thing was from a quick glimpse over the build logs. Maybe 
i have just looked with crooked eyes.

**Comment by chereskata** [comment]
> Is s390x big endian?

I had to look it up 
[here](https://docs.gitlab.com/omnibus/development/s390x.html), it says 
big endian.

**Comment by chereskata** [comment]
Unfortunately it does not work, see [here](https://gitlab.alpinelinux.org/chereskata/aports/-/jobs/1112759)

**Comment by strager** [comment]
@chereskata Can you try again (Git commit 23b30995dc2bb0e6baa6b0113d2af6f7fc445dfb)?

If it doesn't work, I guess I gotta figure out how to emulate a big endian machine. (I have a MIPS router, but I don't think it'll fit quick-lint-js. xD)
