### ISSUE TITLE
Implement is_identifier_character using JS regexp (wasm)

### ISSUE THREAD

**Issue by strager** [quick-lint/quick-lint-js#113]
After compilation, lex-unicode.cpp is huge. This increases download time for quick-lint-js, making the demo less fun.

JavaScript regular expressions can match based on Unicode character properties (e.g. `/\p{L}/u` for letters). For wasm-compiled code which runs in Node.js and in the browser, implement lexer::is_identifier_character and lexer::is_initial_identifier_character using JavaScript regexps instead of the existing lookup table.

I estimate this'll reduce uncompressed download sizes by about 130 KiB, and reduce compressed download sizes by about 30 KiB.

**Comment by CodeItQuick** [comment]
Dibs!

**Comment by strager** [comment]
Given #542, I think this task is a bad idea. We want our own tables to support different Unicode versions.
