### ISSUE TITLE
false positives with Preact code

### ISSUE THREAD

**Issue by strager** [quick-lint/quick-lint-js#1152]
Preact uses attribute names like `class` but quick-lint-js reports diagnostics for this.

Report: https://twitter.com/Hasen_Judi/status/1741916636687610004

**Comment by FlatMapIO** [comment]
When I finished writing the issue I found this 🤣, I want it to be able to read tsconfig.json.

**Comment by Kostas-Xafis** [comment]
+1 I was just about to open an issue too

**Comment by jonathankowalski** [comment]
Same with Solid

**Comment by strager** [comment]
Fixed the false positives in Git commit 6b3fdbed0c2c293b13817c0bfd1466e757988a93. Added a config option in Git commit 9dd47102fbe8af387c2d4b46512a829e89037789: https://quick-lint-js.com/errors/jsx/.

These fixes will end up in the upcoming 3.1 release.

**Comment by strager** [comment]
Version 3.1.0 has shipped with the fix. (It actually shipped 4 days ago, but I forgot to mention it here...)
