### ISSUE TITLE
Method overrides defined with comma at the end of the line show error

### ISSUE THREAD

**Issue by KraXen72** [quick-lint/quick-lint-js#1171]
![image](https://github.com/quick-lint/quick-lint-js/assets/21956756/85506856-e898-4135-bb6d-2f31668fcd01)
![image](https://github.com/quick-lint/quick-lint-js/assets/21956756/4a8fd5c1-4680-43c9-bb10-7daf8971ec06)

replacing `,` with `;`  works, but typescript allows both.

**Comment by strager** [comment]
Fixed in commit 4e6038e5e38450f43a8847923251e57027cbecd7. The fix will be released in quick-lint-js version 3.1.0.

Thanks for reporting!

**Comment by KraXen72** [comment]
thanks 4 the quick fix!

**Comment by strager** [comment]
Version 3.1.0 has shipped with the fix. (It actually shipped 4 days ago, but I forgot to mention it here...)
