### ISSUE TITLE
10$: Warn on let ({x} = y);

### ISSUE THREAD

**Issue by strager** [quick-lint/quick-lint-js#1203]
Before refactor:
```javascript
let x;
({x} = y);
```
After refactor:
```javascript
let ({x} = y);  // Bug! This uses an undeclared variable 'x' and calls a function named 'let'.
```

Conditions for this diagnostic:
* Function call with a variable `let` as the callee.
* Exactly one function argument.
* Function argument is an assignment expression with `=`.
* Function argument's left-hand side is an object literal.

**Comment by msharipov** [comment]
@strager Shouldn't this be considered an error? Code like this crashes in Node.js on line 5:
```
const y = {x: 45, z: "helloworld"};
let z;
({z} = y)
console.log(z);
let ({x} = y);
console.log(x);
```

**Comment by strager** [comment]
@msharipov This doesn't crash:
```javascript
const y = {x: 45, z: "helloworld"};
let z;
({z} = y);
console.log(z);

function let(arg) {
  console.log("let", arg);
}
let x;
let ({x} = y);
console.log(x);
```

**Comment by msharipov** [comment]
@strager Ah, I see. Could you please assign this to me?

**Comment by Nyx1on** [comment]
I claim this for-hire task. I expect payment after I complete this task. I will email the quick-lint-js team if I am assigned this task.

**Comment by strager** [comment]
@Nyx1on Someone else already claimed this task. If @msharipov is unresponsive, I'll give the task you @Nyx1on.

**Comment by msharipov** [comment]
I'm still working on this, it's just taking a while.
