### ISSUE TITLE
10$: warn on 'typeof x === undefined'

### ISSUE THREAD

**Issue by strager** [quick-lint/quick-lint-js#1207]
`typeof x === undefined` is always false. `typeof` returns a string. The programmer meant `typeof x === "undefined"` instead.

**Comment by Master-Helix** [comment]
Hi brother. Can I implement the changes required in this fix?

**Comment by strager** [comment]
@Master-Helix Sure! Here's our contributor guide: https://quick-lint-js.com/contribute/ Let me know if you need more assistance.

**Comment by Master-Helix** [comment]
We have to make the changes everywhere in the repo for typeof x === undefined right?

**Comment by strager** [comment]
@Master-Helix What do you mean by 'everywhere in the repo'? For this task you definitely won't need to change (or even look at) most source files in quick-lint-js.

**Comment by Master-Helix** [comment]
You have tagged it under the C++ domain but it is related to JS files.  And I can see the changes required are already there

**Comment by strager** [comment]
> You have tagged it under the C++ domain but it is related to JS files.

quick-lint-js is a JavaScript checker/linter. quick-lint-js is written in C++. For this task you will be modifying C++ code.

>  And I can see the changes required are already there

I don't know what changes you're referring to. I pasted `typeof x === undefined` into the [quick-lint-js playground](https://quick-lint-js.com/demo/) and saw no diagnostics/warnings.

**Comment by Master-Helix** [comment]
> > You have tagged it under the C++ domain but it is related to JS files.
> 
> quick-lint-js is a JavaScript checker/linter. quick-lint-js is written in C++. For this task you will be modifying C++ code.
> 
> > And I can see the changes required are already there
> 
> I don't know what changes you're referring to. I pasted `typeof x === undefined` into the [quick-lint-js playground](https://quick-lint-js.com/demo/) and saw no diagnostics/warnings.

I understood. Continuing on the fix

**Comment by Master-Helix** [comment]
> > You have tagged it under the C++ domain but it is related to JS files.
> 
> quick-lint-js is a JavaScript checker/linter. quick-lint-js is written in C++. For this task you will be modifying C++ code.
> 
> > And I can see the changes required are already there
> 
> I don't know what changes you're referring to. I pasted `typeof x === undefined` into the [quick-lint-js playground](https://quick-lint-js.com/demo/) and saw no diagnostics/warnings.

![image](https://github.com/quick-lint/quick-lint-js/assets/87581340/c2da0a3e-94b7-41b9-9430-6773e4e7f00e)

I can see the red warning under typeof.

**Comment by strager** [comment]
> I can see the red warning under typeof.

Hmm, did you make code changes? I don't see what you see:
<img width="556" alt="Screenshot 2024-03-05 at 00 09 23" src="https://github.com/quick-lint/quick-lint-js/assets/48666/ffa8b21c-645a-4761-a2a9-b0b6e1fcf8ae">
```javascript
const x = undefined;

if (typeof x === undefined) {
  console.log("x is undefined");
}
```

**Comment by Master-Helix** [comment]
No brother. I am running this directly from your master branch without making any changes. Can you confirm it ?

**Comment by vegerot** [comment]
> > I can see the red warning under typeof.
> 
> Hmm, did you make code changes? I don't see what you see: <img alt="Screenshot 2024-03-05 at 00 09 23" width="556" src="https://private-user-images.githubusercontent.com/48666/309989823-ffa8b21c-645a-4761-a2a9-b0b6e1fcf8ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MTY0MTAsIm5iZiI6MTcwOTYxNjExMCwicGF0aCI6Ii80ODY2Ni8zMDk5ODk4MjMtZmZhOGIyMWMtNjQ1YS00NzYxLWEyYTktYjBiNmUxZmNmOGFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDA1MjE1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzNDQ4MGQ1OGUyZDk5MDQ5NTg4YTEwZjM4OThmNDJiZjI1NWM2MWQ0N2ZjM2M4NDA3YjgxM2E2Yjc3MWJiMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CZ-_veJuyyFicvwt4yDY-O_hNGSq1qT4kPcF7iErzxI">
> 
> ```js
> const x = undefined;
> 
> if (typeof x === undefined) {
>   console.log("x is undefined");
> }
> ```

I can reproduce by typing `typeof` with the mathematical sans-serif small 𝗉.


```js
const x = undefined;

if (ty𝗉eof x === undefined) {
  console.log("x is undefined");
}
```

![image](https://github.com/quick-lint/quick-lint-js/assets/5297725/e507f1a0-b84e-4303-b689-41d63a2e0483)

**Comment by Master-Helix** [comment]
I guess the issue is with the font on the playground then ? The syntax should work irrespective of the font used

**Comment by strager** [comment]
@Master-Helix On the demo, can you run `JSON.stringify(document.querySelector('textarea').textContent)` in the browser's JS console and share the result? This will help rule out issues like what @vegerot mentioned.

**Comment by Master-Helix** [comment]
> @Master-Helix On the demo, can you run `JSON.stringify(document.querySelector('textarea').textContent)` in the browser's JS console and share the result? This will help rule out issues like what @vegerot mentioned.

Sure. 

![image](https://github.com/quick-lint/quick-lint-js/assets/87581340/e11eec2f-08cb-43e6-b5fa-9e788c3578fe)

**Comment by CoderMuffin** [comment]
I would be interested in attempting to resolve this issue unless either of @Master-Helix or @vegerot wanted to? (I am only asking because I saw the unassignment)

**Comment by strager** [comment]
@CoderMuffin Sure, you can tackle this task.

**Comment by CoderMuffin** [comment]
@strager Not sure if you get notified so I just wanted to let you know that I have submitted a pull request with the first draft for these changes :)
