### ISSUE TITLE
Error use of undeclared type on types defined in `.d.ts` files

### ISSUE THREAD

**Issue by lifeisfakenews** [quick-lint/quick-lint-js#1214]
I am getting the error `use of undeclared type` on `Tournament` for the following code:

```ts
const tournament = query.data() as Tournament;
tournament.id = query.id;
```

even though, in vsc i can ctrl click on `Tournament` and it takes me to the definition in my `types.d.ts` file.

i can even hover it and it will show me the type information
![image](https://github.com/quick-lint/quick-lint-js/assets/86294896/c21a3fe6-1169-4d18-99b4-a84d5c615ba0)

**Comment by strager** [comment]
Yeah, this looks to be the same issue as #1172. Currently quick-lint-js does not respect `declare global` in .d.ts files like this. I wrote some possible solutions in this comment: https://github.com/quick-lint/quick-lint-js/issues/1172#issuecomment-1884011471

> Some possible solutions:
> 1. Rewrite your code to use `import` instead of globals.
> 2. Manually replicate app.d.ts to your quick-lint-js.config.
> 3. Use a tool which replicates app.d.ts's globals to your quick-lint-js.config. (This tool does not yet exist.)
> 4. Use a `"globals-files"` feature in quick-lint-js.config to specify source files. You would list `"globals-files": ["src/app.d.ts"]`. (This feature does not yet exist.)
> 5. Have quick-lint-js auto-scan for .ts and .d.ts files which declare globals, similar to what TypeScript's compiler does. (This feature does not yet exist.)

I'm closing this as a duplicate.
