### ISSUE TITLE
feature request: add DOM types to builtin symbol list

### ISSUE THREAD

**Issue by vegerot** [quick-lint/quick-lint-js#1216]
quick-lint doesn't know of the DOM types from [TypeScript's dom.d.ts](https://github.com/microsoft/TypeScript/blob/main/src/lib/dom.generated.d.ts), causing me to get false-positive squiggles 

<img width="665" alt="image" src="https://github.com/quick-lint/quick-lint-js/assets/5297725/1be38496-5d30-46f8-bce0-9fb775dc32d7">
 
It'd be nice if quick-lint knew all of these types so I wouldn't have to manually add them to my quick-lint config file

**Comment by strager** [comment]
Fixed in Git commit 456e77433dc3464eeb2422f908096e2255897027. If there are any other types I missed, let me know.
