### ISSUE TITLE
Website: dark mode

### ISSUE THREAD

**Issue by strager** [quick-lint/quick-lint-js#127]
Create a dark mode theme for the website.

**Comment by LeeWannacott** [comment]
Could possibly try using: https://www.npmjs.com/package/darkmode-js

**Comment by strager** [comment]
> Could possibly use this library: https://www.npmjs.com/package/darkmode-js

A configuration widget sounds like overkill for a basic webpage like quicklintjs.com.

I'd prefer a modest sprinkle of [`prefers-color-scheme`](https://developer.mozilla.org/en-us/docs/Web/CSS/@media/prefers-color-scheme).

**Comment by LeeWannacott** [comment]
I didn't know that existed, I should read over the MDN Web Docs to become aware of what exists. 

I can have a go at implementing this challenging issue if you wish.

**Comment by strager** [comment]
> I can have a go at implementing this challenging issue if you wish.

Sure, you may hack on this task.

**Comment by strager** [comment]
Deployed dark mode at commit b9451e223fb30fb0e271a44732e39a317754ffcc (https://github.com/quick-lint/quick-lint-js/actions/runs/598272894).
