### ISSUE TITLE
🐛 Bug: False positive "use of undeclared variable"

### ISSUE THREAD

**Issue by vegerot** [quick-lint/quick-lint-js#154]
Can't really give much context, since I did not experience this issue.  @[skywalk](https://discord.com/channels/640652660839677962/640652660839677964/805549911189225503) did and was too lazy to make an issue here, so I offered to do it for him.

Picture: 

![](https://cdn.discordapp.com/attachments/640652660839677964/805549911151607869/unknown.png)

code: https://bpa.st/7U54W

**Comment by strager** [comment]
This was caused by a crash in quick-lint-js, and the diagnostics subsequently getting out of sync. Commit 774e4da428d59d3de8cd2225be652573ddb29f61 fixed the crash. The out-of-sync issue is a probably-won't-fix; I'd rather fix quick-lint-js crashes (issue #109).
