### ISSUE TITLE
12$: Web demo leaks memory

### ISSUE THREAD

**Issue by strager** [quick-lint/quick-lint-js#163]
Web demo leaks memory and eventually crashes.

**Comment by vegerot** [comment]
more description, for whoever picks it up: https://clips.twitch.tv/ShortTemperedOwlBCWarrior-jIKB0x7dem23u2TC

**Comment by strager** [comment]
I think #313 should make this task really easy to fix.

**Comment by strager** [comment]
Fixed by virtue of fixing #313.
