### ISSUE TITLE
Improve self-documentation of generated files

### ISSUE THREAD

**Issue by strager** [quick-lint/quick-lint-js#167]
ADR004:

> It's sometimes unclear if a file which is checked into the repository is generated. This means that a contributor might modify files, but their modifications might be destroyed when the unorthodox tool is re-run to re-generate those manually-modified files.

Let's fix this problem by making the generated files self-documenting somehow. Perhaps just a comment at the top saying "this is generated; run command XYZ to regenerate".

- [ ] src/lex-keyword.cpp
- [x] src/lex-unicode.cpp
- [ ] src/translation-table-generated.cpp
- [ ] src/quick-lint-js/translation-table-generated.h
- [ ] translation .po files
- [ ] doc/man/ files

**Comment by k1ng440** [comment]
may i claim this issue?

**Comment by strager** [comment]
I think I had this in mind but I didn't write it: We should include "generated" in all the file names if possible (it's not possible for the man pages, but perhaps we can create a "generated" directory).
