### ISSUE TITLE
VSCode: Extension causes high cpu load.

### ISSUE THREAD

**Issue by LeeWannacott** [quick-lint/quick-lint-js#192]
- Issue Type: `Performance`
- Extension Name: `quick-lint-js`
- Extension Version: `0.1.0`
- OS Version: `Linux x64 5.8.0-7642-generic`
- VSCode version: `1.54.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/tmp/quick-lint.quick-lint-js-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

[quick-lint.quick-lint-js-unresponsive.cpuprofile.txt](https://github.com/quick-lint/quick-lint-js/files/6250801/quick-lint.quick-lint-js-unresponsive.cpuprofile.txt)

**Comment by strager** [comment]
Known issue, fixed in commit 92e75aeca4511bc92716c93998ced0b5f0a3edbc. I should deploy a new version of the VS Code plugin.

**Comment by strager** [comment]
Version 0.2.0 shipped with the fix.
