### ISSUE TITLE
7$: CI: Detect broken links on website

### ISSUE THREAD

**Issue by strager** [quick-lint/quick-lint-js#194]

**Comment by backbugkaught** [comment]
I claim this for-hire task. I expect payment after I complete this task. I will email the quick-lint-js team if I am assigned this task.

**Comment by backbugkaught** [comment]
```python
#!/usr/bin/env python3
import requests
import re
from bs4 import BeautifulSoup
from urllib.parse import urljoin, urlparse
import argparse

"""
(error_message), url, broken_url
"""

mail_whitelist = "whitelist_mail.txt"
hash_urls = []


def is_mailto_link(link) -> bool:
    return True if re.search(r"^mailto:*", link) else False


def readfile(filename) -> list:
    try:
        with open(filename, "r") as f:
            return list(map(lambda x: x.strip("\n"), f.readlines()))
    except BaseException:
        return []


def in_mail_whitelist(link, filename=mail_whitelist) -> bool:
    return True if link in readfile(filename) else False


def in_namespace(namespace, url) -> bool:
    return urlparse(url).netloc == namespace


def get_urls_from_page(url) -> list:
    req = requests.get(url)
    soup = BeautifulSoup(req.text, "html.parser")
    href_tags = soup.find_all(href=True)
    hrefs = [tag.get("href") for tag in href_tags]
    return hrefs


def return_mail_address(link) -> str:
    return link.split(":")[1]


def crawl_and_report(parent_url, site_namespace, urls):
    # report broken urls on parent page
    # if url is in "namespace" then crawl that page
    for i in urls:
        if is_mailto_link(i):
            mail_link = return_mail_address(i)
            if not in_mail_whitelist(mail_link):
                print(f"(unknown mail) {parent_url}, {mail_link}")
        else:
            url = urljoin(parent_url, i)
            if url not in hash_urls:
                hash_urls.append(url)
                result = requests.get(url)
                if result.ok and in_namespace(site_namespace, result.url):
                    urls_from_page = get_urls_from_page(result.url)
                    if len(urls_from_page) != 0:
                        crawl_and_report(
                            result.url, site_namespace, urls_from_page)
                elif not result.ok:
                    print(
                        f"({result.status_code} error) {parent_url}, {url}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--site", type=str)
    args = parser.parse_args()
    if args.site:
        site = args.base_url
    else:
        site = "https://quick-lint-js.com/"
    site_namespace = urlparse(site).netloc
    urls = get_urls_from_page(site)
    crawl_and_report(site, site_namespace, urls)
```

**Comment by strager** [comment]
@backbugkaught 

* Let's embed `mail_whitelist` into the source code. No need for a separate file.
* I ran the program, and it look longer to run than I expected. I'd imagine this script should take 5 seconds or less. What gives?
  * The script seems to download https://quick-lint-js.com/install.html and https://quick-lint-js.com/install.html#manual-cli and https://quick-lint-js.com/install.html#manual-vscode separately. Perhaps this is part of the problem?
  * The script seems to download the contents of files in https://c.quick-lint-js.com/. It should only download the headers, not the contents, since the contents won't be inspected anyway.
* The program doesn't check the validity of fragments. E.g. it doesn't check that install.html has a #manual-vscode element.
* Include an install script, documentation, or requirements.txt.
* Make a CI script to run this script.
* On my machine, Reddit is giving us 429 responses: `(429 error) https://quick-lint-js.com/, https://old.reddit.com/r/javascript/comments/j4zj3c/rslint_an_extremely_fast_javascript_linter/g7r46mp/?context=1`
* We should have an option to not check external links (opt in or opt out). Idea:
  * On pull requests, only check internal links. This will reduce test flakiness in case external services are flaky (e.g. Reddit is down).
  * Daily, check external links.

**Comment by strager** [comment]
> I will email the quick-lint-js team if I am assigned this task.

I haven't received your email yet.

**Comment by strager** [comment]
This isn't done yet. This task was closed accidentally.
