### ISSUE TITLE
22$: Add performance tracing to VS Code plugin

### ISSUE THREAD

**Issue by strager** [quick-lint/quick-lint-js#196]
Idea for an append-only recoverable format:

```
timestamp file-id file-path-or-duration
```
```
10000 1 index.js
10010 1 12451
10011 1 412
10011 1 41231
10012 1 3121
10012 1 2415
25000 2 other.js
30201 2 12812
30240 1 1412
```

**Comment by lifeinData** [comment]
I'm working on this. Will let you know if I'm completely stuck.

**Comment by strager** [comment]
A simpler format would be something like this:
```
10010 12451 index.js
10011 412 index.js
10011 41231 index.js
10012 3121 index.js
10012 2415 index.js
30201 12812 other.js
30240 1412 index.js
```
I suggested the more complicated format earlier because it'd produce smaller files. (Repeating the file name, especially if it is long, might produce relatively big files.) `file-id` was a way to compress the file name into a number.

**Comment by lifeinData** [comment]
currently tracking on #244
