### ISSUE TITLE
7$: Report warnings for misuse of --vim-file-bufnr

### ISSUE THREAD

**Issue by strager** [quick-lint/quick-lint-js#201]
* `--vim-file-bufnr` without following file name
* `--vim-file-bufnr` with an `--output-format` which doesn't use `--vim-file-bufnr`
* `--vim-file-bufnr` in `--lsp-server` mode (see discussion in #202)

**Comment by rol1510** [comment]
Do we need the following warning?
> --vim-file-bufnr in --lsp-server mode (see discussion in https://github.com/quick-lint/quick-lint-js/issues/202)

Because we already have the following warning:
> warning: ignoring files given on command line in --lsp-server mode

and with
> --vim-file-bufnr without following file name

it is redundant, or am I missing something?

**Comment by strager** [comment]
@rol1510 If the command line is `--lsp-server --vim-file-bufnr=42`, then I think an error message of "warning: --vim-file-bufnr is missing a file name" is confusing. I think "warning: ignoring --vimfile-bufnr in --lsp-server mode" is a better message in this case.

**Comment by rol1510** [comment]
Good point. Should both appear or do I have to block "warning: --vim-file-bufnr is missing a file name"?

**Comment by strager** [comment]
> Should both appear or do I have to block "warning: --vim-file-bufnr is missing a file name"?

I'd prefer just "warning: ignoring --vimfile-bufnr in --lsp-server mode" in this case.
