### ISSUE TITLE
7$: Report warnings for misuse of --lsp-server

### ISSUE THREAD

**Issue by strager** [quick-lint/quick-lint-js#202]
If `--lsp-server` is combined with options like `--output-format` and `--vim-file-bufnr`, issue a warning explaining that `--output-format` won't be used.

**Comment by strager** [comment]
#208 issued a warning for `--output-format`, but no warning is issued for other options like `--vim-file-bufnr` and `--exit-fail-on`.

**Comment by LiraNuna** [comment]
This was fixed by https://github.com/quick-lint/quick-lint-js/pull/208

@strager I suggest you use github's merge function which would've also closed this issue.
This issue can be closed.

**Comment by LiraNuna** [comment]
@strager doesn't `vim-file-bufnr` need `files_to_lint` as well? Wouldn't a better error/warning be if `--vim-file-bufnr` is left unused?

**Comment by strager** [comment]
> @strager doesn't `vim-file-bufnr` need `files_to_lint` as well?

Yes. #201 mentions this.

> Wouldn't a better error/warning be if `--vim-file-bufnr` is left unused?

Assuming both --lsp-server and --vim-file-bufnr are given, here's my opinion on warning messages:
* "missing file after --vim-file-bufnr": confusing
* "--vim-file-bufnr is unused because no files follow it": confusing
* "--vim-file-bufnr option is unused": okay
* "--vim-file-bufnr does nothing because of --lsp-server": great

**Comment by LiraNuna** [comment]
since `--vim-file-bufnr` is only handled in `parse_options`, what is your opinion on collecting them into the `options` struct and zipping them later, to allow error handling to be done inside `dump_errors`?

**Comment by strager** [comment]
> since `--vim-file-bufnr` is only handled in `parse_options`, what is your opinion on collecting them into the `options` struct and zipping them later, to allow error handling to be done inside `dump_errors`?

That sounds good, assuming the code isn't terribly complicated. (This is C++, after all. Good luck!)

**Comment by LiraNuna** [comment]
Actually, I don't think this will work since the order of arguments matter. Right now I could argue that [given this check in options.cpp](https://github.com/quick-lint/quick-lint-js/blob/master/src/options.cpp#L211-L214), it's sufficient to not check `--vim-file-bufnr` as an lsp-server warning.

Instead, I could argue that having `--vim-file-bufnr` unattached to a file name should be issuing a warning regardless of lsp mode.

Would you consider this correct? If so, should this be closed or are there any other options you think should be addressed?

**Comment by strager** [comment]
> Actually, I don't think this will work since the order of arguments matter. Right now I could argue that [given this check in options.cpp](https://github.com/quick-lint/quick-lint-js/blob/master/src/options.cpp#L211-L214), it's sufficient to not check `--vim-file-bufnr` as an lsp-server warning.

That makes total sense. 

> Instead, I could argue that having `--vim-file-bufnr` unattached to a file name should be issuing a warning regardless of lsp mode. (See #201)

I think this is a good solution. `--vim-file-bufnr` is a rare option anyway, so we don't need to make custom diagnostics for every possible situation.

> Would you consider this correct?

Yup! For completeness, I updated issue #201 to mention `--lsp-server`.
