### ISSUE TITLE
10$: Report warning on using function declared in inner scope

### ISSUE THREAD

**Issue by strager** [quick-lint/quick-lint-js#210]
The following code behaves differently on different JavaScript VMs:

```js
f();
{
  function f() { print("hello"); }
}
```

(This is codified in the standard: B.3.3 Block-Level Function Declarations Web Legacy Compatibility Semantics)

JavaScriptCore: `hello`
SpiderMonkey: TypeError: f is not a function
V8: TypeError: f is not a function

Make quick-lint-js report a warning for this code.

**Comment by singalhimanshu** [comment]
I claim this for-hire task. I expect payment after I complete this task. I will email the quick-lint-js team if I am assigned this task.
