### ISSUE TITLE
Add <meta description> to website for SEO goodness

### ISSUE THREAD

**Issue by strager** [quick-lint/quick-lint-js#213]

**Comment by 0xbiel** [comment]
doing it rn.

**Comment by strager** [comment]
Waiting for Google to pick it up.

**Comment by strager** [comment]
According to Google Search Console, the home page has been indexed with the new `<meta>` tag. However, search results on Google still show the auto-generated description. DuckDuckGo similarly shows auto-generated descriptions in its results, not the hand-written description.

Any idea what might be wrong?

**Comment by 0xbiel** [comment]
Hmm that's weird.

I made some research and this might be an explanation:

> In cases where Google believes the existing and optimised meta-description to be “too badly written” or “inappropriate”, when compared to the content of the page and/or the user's specific search phrase, they will not show this description in the SERPs (Search Engine Result Pages).

**Comment by strager** [comment]
If I search `try quick-lint-js` on Google, I get the <meta description>:

> https://quick-lint-js.com
> **quick-lint-js finds JavaScript bugs**
> **quick-lint-js** gives you instant feedback as you code. Find bugs in your JavaScript before your finger leaves the keyboard.

So I guess it's working, but not if you search just `quick-lint-js`:

> https://quick-lint-js.com
> **quick-lint-js finds JavaScript bugs**
> **quick-lint-js**. **quick-lint-js** finds bugs in JavaScript programs. ... **quick-lint-js** gives you instant feedback as you code. Find bugs in your JavaScript before your finger ...

Weird. I guess it's working.
