### ISSUE TITLE
10$: Error on use of `this.#something` outside of class

### ISSUE THREAD

**Issue by strager** [quick-lint/quick-lint-js#219]
Private identifiers in dot expressions (e.g. `this.#something`) are only legal inside of a class. Report an error if such an expression is found outside a class.

**Comment by strager** [comment]
I think we'd need to track whether or not we're in a class declaration. We don't do this currently. (We do track whether or not we're in a function or a loop, though; perhaps we could have similar logic for classes.)

**Comment by saurabhraj042** [comment]
@strager Can I work on this issue ?

**Comment by strager** [comment]
@saurabhraj042 Sure!

**Comment by singalhimanshu** [comment]
@saurabhraj042 Are you still working on it? If not I can work on this issue.

**Comment by saurabhraj042** [comment]
@strager @singalhimanshu please give me few more days to work on this , actually I got covid last month and wasn't able to work on this but I have resumed the work for now.

**Comment by singalhimanshu** [comment]
@strager I would like to work on this task.
