### ISSUE TITLE
Error on invalid hex escape sequences: "hello\x1qworld"

### ISSUE THREAD

**Issue by strager** [quick-lint/quick-lint-js#22]
String literals can contain hexadecimal escape sequences (starting with `\x`). If the escape sequence is invalid, quick-lint-js should report an error. Teach quick-lint-js about such errors in lex.cpp, error.h, and test-lex.cpp.

**Comment by AngelJA** [comment]
Started a WIP PR: #156 

Just started probing though.  Hoping for some feedback on stream.
