### ISSUE TITLE
12$: Document CLI on website

### ISSUE THREAD

**Issue by strager** [quick-lint/quick-lint-js#224]

**Comment by strager** [comment]
[Asciidoctor](https://asciidoctor.org/) might help with this. We could write the documentation in AsciiDoc and generate a man page and an HTML page from the AsciiDoc.

**Comment by DGKSK8LIFE** [comment]
I claim this for-hire task.

**Comment by DGKSK8LIFE** [comment]
#227

**Comment by strager** [comment]
I think @DGKSK8LIFE wants to give up this task:
> @strager I'm happy to pass this on to someone else if they're willing to complete the task. Thanks
> https://github.com/quick-lint/quick-lint-js/pull/227#issuecomment-821878330

**Comment by erlliam** [comment]
I'm interested in this issue. I will claim it for hire once I learn Asciidoctor.

**Comment by erlliam** [comment]
I claim this for-hire task. I expect payment after I complete this task. I will email the quick-lint-js team if I am assigned this task.

**Comment by strager** [comment]
@erlliam I didn't receive an email from you yet.
