### ISSUE TITLE
Website: logo and favicon.ico

### ISSUE THREAD

**Issue by strager** [quick-lint/quick-lint-js#273]

**Comment by Yulinka** [comment]
I’m working on it

**Comment by strager** [comment]
Places we can use the logo:

- [ ] Website favicon
- [ ] Website header
- [ ] GitHub README
- [ ] GitHub social preview
- [ ] VS Code README
- [ ] VS Code extension pop-up (maybe)
- [ ] .exe icon

**Comment by strager** [comment]
I put @Yulinka's artwork in a few places.

We should redo the favicon. (I made it on my own. Sue me.) After that, I think this task is done.

**Comment by strager** [comment]
My own favicon is good 'nuff for 1.0.
