### ISSUE TITLE
Add --snarky option

### ISSUE THREAD

**Issue by strager** [quick-lint/quick-lint-js#3]

**Comment by vegerot** [comment]
dibs too

**Comment by strager** [comment]
I'm currently overhauling quick-lint-js' error system. The overhaul will make it easy to add translations, and we could implement --snarky as a translation.

I suggest waiting until I complete the rewrite.

**Comment by strager** [comment]
The error system has been rewritten. We can now build a translation system, and build a snarky translation.

**Comment by vegerot** [comment]
Well let me know when you're ready for some writers

**Comment by strager** [comment]
Translation infrastructure was introduced in commit 42db1be9676a8242538e3db06ad2cf1a1932c701. It should be straightforward to create po/en@snarky.po now.

**Comment by strager** [comment]
If you create po/en@snarky.po, you'd run ./tools/compile-translations and rebuild quick-lint-js, then test by running quick-lint-js' CLI with `LANGUAGE=en@snarky`.

**Comment by strager** [comment]
I think these steps are necessary to complete this task:

- [ ] Run `./tools/compile-translations` to create an `en_US@snarky` translation.
- [ ] Write some snarky translations.
- [ ] Add code to parse the --snarky option in src/options.cpp and test/test-options.cpp.
- [ ] Add code to set the language to the `@snarky` variant based on the --snarky option in src/main.cpp or src/translation.cpp or both.

**Comment by DaviddHub** [comment]
Hello

**Comment by strager** [comment]
Implemented in b624c250948fcedfb7f197b305ceb00e4c8eaf01. (Thanks, @DaviddHub!)
