### ISSUE TITLE
7$: Improve diagnostic for: let x new Array();

### ISSUE THREAD

**Issue by strager** [quick-lint/quick-lint-js#304]
In the following code, the user probably meant to put an `=` between `x` and `new`:
```js
let x new Array();
```
quick-lint-js provides a suboptimal message:
```
error: missing semicolon after statement [E027]
```
Improve this message for the case where a `=` would work well.

**Comment by singalhimanshu** [comment]
I claim this for-hire task. I expect payment after I complete this task. I will email the quick-lint-js team if I am assigned this task.

**Comment by singalhimanshu** [comment]
> Improve this message for the case where a `=` would work well.

Should we show both errors (`missing semicolon` and `missing equal`) or just (`missing equal`).

**Comment by strager** [comment]
> > Improve this message for the case where a `=` would work well.
> 
> Should we show both errors (`missing semicolon` and `missing equal`) or just (`missing equal`).

Only `missing equal`.
