### ISSUE TITLE
Website loads vscode-demo.mp4 even if .webp is supported

### ISSUE THREAD

**Issue by strager** [quick-lint/quick-lint-js#312]

**Comment by Xanas1252** [comment]
replace <source src="vscode-demo.mp4" type="video/mp4" /> with <source src="vscode-demo.webp" type="video/webp" />
-webp  is supported in most browsers.

**Comment by Xanas1252** [comment]
replace` <source src="vscode-demo.mp4" type="video/mp4" />` with `<source src="vscode-demo.webp" type="video/webp" />`
- webp is supported in all browsers.

**Comment by strager** [comment]
>     * webp is supported in all browsers.

webp is not supported on my Mac's Safari (Version 12.1.2 (14607.3.9)).

webp is also not supported on my phone (running EdgeHTML 13).

**Comment by strager** [comment]
Fixed in commit aa597342aa0d46ceeb28fa10313ca40f2f7c3d8c.
