### ISSUE TITLE
Rename 'error' to 'diag'

### ISSUE THREAD

**Issue by strager** [quick-lint/quick-lint-js#326]
Internally, the term "error" is confusing for new contributors, especially if they want to print a *warning*. Rename 'error' to 'diag' (short for 'diagnostic') to alleviate confusion.

**Comment by singalhimanshu** [comment]
There are a lot of places where the term "error" is used like - `report_error`, `QLJS_X_ERROR_TYPES`, `QLJS_ERROR_TYPE`, `valid_error_codes`, `parsed_error_list` and many more. Do we have to change all these or in some selective places?

**Comment by strager** [comment]
> There are a lot of places where the term "error" is used like - `report_error`, `QLJS_X_ERROR_TYPES`, `QLJS_ERROR_TYPE`, `valid_error_codes`, `parsed_error_list` and many more. Do we have to change all these or in some selective places?

Yes, we'd change all of these. Except the `error_formatter` method named `error`.

**Comment by strager** [comment]
Done from commit c5e8871a325e9b9be565b49a281a69227e4fcb6c through commit 2723904636c3c9063f631c0974626bbe56572dc6. There might be some more references to 'error', but I think I got the main ones.
