### ISSUE TITLE
Post-1.0?

### ISSUE THREAD

**Issue by strager** [quick-lint/quick-lint-js#327]
What should we do after releasing version 1.0?

Some ideas:

* TypeScript (#690)
* JSX (#493)
* translations into other human languages
* new bug-finding rules
* JS embedded in HTML (#116) or Markdown (#117)
* more editor plugins
* automated fixes (#115)
* better error messages for parse errors

Which ideas we pursue will likely depend on feedback.

**Comment by singalhimanshu** [comment]
I think automated fixes will be really helpful for the new programmers to get a hint about how to fix the reported error.

**Comment by juancarlospaco** [comment]
Public documented C API to use it as a library too, 
even a basic one to call it with a string argument.

**Comment by strager** [comment]
> Public documented C API to use it as a library too,
> even a basic one to call it with a string argument.

What is your use case?

**Comment by juancarlospaco** [comment]
Use it as a library, instead of calling it as a subprocess, which is slower and not so elegant.

**Comment by strager** [comment]
> Use it as a library, instead of calling it as a subprocess, which is slower and not so elegant.

What application are you building which needs to integrate with quick-lint-js?

**Comment by KasonBraley** [comment]
Up-voting for TypeScript and JSX support

**Comment by tmcdos** [comment]
Plugin for PhpStorm and/or WebStorm - to replace the built-in ESLint checker/inspector.

**Comment by ffurger** [comment]
Just came across your quick-lint-js.

I wish I could install it as an extension in Nova, the next generation code editor in the Mac designed by Panic.

**Comment by strager** [comment]
> I wish I could install it as an extension in Nova, the next generation code editor in the Mac designed by Panic.

I filed #590 for Nova.

**Comment by strager** [comment]
JSX support was added in version 2.0.0 (#493).

I filed #690 for TypeScript support. That'll be the major feature for 3.0.0.
