### ISSUE TITLE
10$: Man page for error documentation

### ISSUE THREAD

**Issue by strager** [quick-lint/quick-lint-js#331]
We have a web page which documents quick-lint-js' error codes: https://quick-lint-js.com/errors/

Create a manual page (for the UNIXy `man` utility) with the same information.

**Comment by maniac-en** [comment]
I'll take care of this issue.

**Comment by strager** [comment]
Notes from talking with @maniac-en:

website/src/error-documentation.mjs file contains support code, mostly to interpret Markdown files. It loads the files in docs/errors/. website/src/error-documentation.mjs and website/public/errors/index.ejs.html together generate the web page (HTML). We're using Markdown for error documentation.

Here's a hand-written man page for reference: https://github.com/quick-lint/quick-lint-js/blob/c5403d73b62874c61e7042c46877fdd88f42e225/docs/quick-lint-js.1 (Old commit. quick-lint-js.1 is now generated from asciidoc)

For this task, we should be able to create a Markdown-to-man-page thingy in error-documentation.mjs.
We'd need to create an entire rule set, which shouldn't be too hard 'cus Markdown is relatively small.

Tests exist for website/test/test-error-documentation.mjs, but the HTML generation tests are sparse.

The Markdown-to-HTML converter shows error squigglies (<mark>). We should do the same for the man page. (markEditorText is complicated because it's used for the demo on the website. You could write something much simpler for Markdown-to-man.)

**Comment by strager** [comment]
Nah, no one uses man pages like this. Let's abandon this task.
