### ISSUE TITLE
10$: Website: fix validation failures

### ISSUE THREAD

**Issue by strager** [quick-lint/quick-lint-js#335]
https://validator.nu/?doc=https%3A%2F%2Fquick-lint-js.com%2F

**Comment by jgil-r** [comment]
I claim this for-hire task. I expect payment after I complete this task. I will email the quick-lint-js team if I am assigned this task.

**Comment by strager** [comment]
@jgil-r Did you look at all other pages for validation errors?

**Comment by jgil-r** [comment]
I didn't, I'll take a look right now.

**Comment by jgil-r** [comment]
@strager I found a bunch of other validation errors. Ill fix them and submit a new pull request.

**Comment by strager** [comment]
These pages still have validator errors or warnings:

* https://quick-lint-js.com/license/
* https://quick-lint-js.com/hiring/
* https://quick-lint-js.com/benchmarks/ (but I don't care about the type=module warning)

**Comment by strager** [comment]
Thanks for the fixes.
