### ISSUE TITLE
5$: Missing ASI for 'if (true)'

### ISSUE THREAD

**Issue by strager** [quick-lint/quick-lint-js#342]
qljs reports an error for the following valid code:
```js
if (true)
```
I think this is valid because a semicolon can be inserted after `)` to make it valid.

Perhaps we should make this a warning, not an error.

**Comment by strager** [comment]
Hmm, Node.js rejects this code:
```
$ cat hello.js
if (true)
$ node hello.js
/Users/strager/Projects/quick-lint-js/hello.js:2



SyntaxError: Unexpected end of input
    at wrapSafe (node:internal/modules/cjs/loader:1024:16)
    at Module._compile (node:internal/modules/cjs/loader:1072:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47
```

Maybe it *is* invalid. I wonder why ASI wouldn't kick in here.

**Comment by strager** [comment]
Manual experiments show that major JS engines reject a file containing just `if (true)`. My interpretation of the standard also says that `if (true)` is invalid.

# JS standard

https://tc39.es/ecma262/#sec-rules-of-automatic-semicolon-insertion

> 2. When, as the source text is parsed from left to right, the end of the input stream of tokens is encountered and the parser is unable to parse the input token stream as a single instance of the goal nonterminal, then a semicolon is automatically inserted at the end of the input stream.
>
> [...]
>
> However, there is an additional overriding condition on the preceding rules: **a semicolon is never inserted automatically if the semicolon would then be parsed as an empty statement** or if that semicolon would become one of the two semicolons in the header of a for statement (see 14.7.4).

# Experiments

Firefox browser, version 88.0.1 (64-bit) for macOS, external script:
> Uncaught SyntaxError: expected expression, got end of script

Safari browser, version 12.1.2 (14607.3.9) for macOS, external script:
> SyntaxError: Unexpected end of script

Brave browser, version 1.23.73 Chromium: 90.0.4430.85 (Official Build) (x86_64) for macOS, external script:
> Uncaught SyntaxError: Unexpected end of input

Node.js, main script:
> SyntaxError: Unexpected end of input

test-all-js-engines:
```
$ ./tools/test-all-js-engines hello.js
#### JavaScriptCore

SyntaxError: Unexpected end of script

#### SpiderMonkey

SyntaxError: expected expression, got end of script

#### V8

SyntaxError: Unexpected end of input
```

**Comment by strager** [comment]
@singalhimanshu I couldn't reproduce the test-all-js-engines behavior you saw. I am pretty sure that quick-lint-js is doing the right thing.

**Comment by singalhimanshu** [comment]
This fixed the `test-all-js-engines` script - https://github.com/quick-lint/quick-lint-js/pull/343
