### ISSUE TITLE
15$: Prune old builds on c.quick-lint-js.com

### ISSUE THREAD

**Issue by strager** [quick-lint/quick-lint-js#367]
c.quick-lint-js.com stores build artifacts created by CI scripts (in the .github/ directory in the repo). It maintains builds for closed PRs and deleted branches.

Idea: Delete builds from c.quick-lint-js.com which:

* are older than 14 days,
* are referenced by no branch, and
* are referenced by no pull request

This will save us some server storage costs.

**Comment by matttheus** [comment]
I claim this for-hire task. I expect payment after I complete this task. I will email the quick-lint-js team if I am assigned this task.

**Comment by strager** [comment]
Builds: https://c.quick-lint-js.com/builds/

If we're going to run the script automatically via GitHub Actions, here are some options:

* SFTP (this is what GitHub Actions uses to upload the builds)
* SSH, run some Bash scripts on c.quick-lint-js (this is what `dist/debian/sync-releases-to-apt` does)

If we're going to run the script via a cron job on the server, we need to access Git commit metadata.

**Comment by matttheus** [comment]
Working on #385. You can follow my work there.

**Comment by strager** [comment]
I deployed @matttheus' script. It's running hourly via cron for the github-ci user on c.quick-lint-js.com.
