### ISSUE TITLE
unexpected keywords in expressions cause fatal errors

### ISSUE THREAD

**Issue by dav000** [quick-lint/quick-lint-js#407]
`// missing open comment`
`no-case-declarations */;`

`../src/parse.cpp:506: fatal: token not implemented in parse_primary_expression: kw_case on line 2 column 4`

**Comment by strager** [comment]
We should end an expression when we see `case`.

**Comment by dav000** [comment]
There is the same or similar issue with these keywords
`break
case
catch
const
continue
default
do
else
export
extends
finally
function
try
var
with`

**Comment by dav000** [comment]
> We should end an expression when we see `case`.

Does end an expression mean simply returning an invalid expression and not reporting an unexpected token error? It would be easy to add all of the keywords to the existing switch case, but there would also be new unhandled fatal errors for a lot of these keywords.
