### ISSUE TITLE
Report warning if number literal will lose precision

### ISSUE THREAD

**Issue by strager** [quick-lint/quick-lint-js#44]
JavaScript interprets the literal `9999999999999999` as the number `10000000000000000`. Report a warning in this case.

- [ ] Research limits of JavaScript integer literals.
- [ ] Create an error type in error.h. (Error types can have a severity of *warning*.)
- [ ] Add some tests for the error cases in test-lex.cpp.
- [ ] Emit the errors in lex.cpp.

**Comment by strager** [comment]
fgffhjkg kjhfjkf gf ghd yrtdcguy f

**Comment by strager** [comment]
njkbnkjb

**Comment by robminer6** [comment]
Do you mind if I handle this issue?
