### ISSUE TITLE
Exit non-zero if any errors

### ISSUE THREAD

**Issue by strager** [quick-lint/quick-lint-js#45]
Note: I think this task needs a bit more C++ skill than other good-first-issue issues.

If quick-lint-js's CLI reports an error in a JavaScript program, it should return a non-zero exit code like other linters. Our CLI currently returns zero always.

Idea for implementation:

1. Create an `error_reporter`-derived class which tracks if any errors were detected, forwarding errors to another `error_reporter` object.
2. In main.cpp, use the wrapping `error_reporter` created in step 1.

**Comment by eiffel-fl** [comment]
I can try to solve this one!
