### ISSUE TITLE
10$: Show release with notes on GitHub

### ISSUE THREAD

**Issue by strager** [quick-lint/quick-lint-js#469]

**Comment by strager** [comment]
Idea: A Go script which uses GitHub's API to sync docs/CHANGELOG.md to GitHub releases. Dunno how to do attachments, but we can start with just the release notes. Should be pretty self-contained.

**Comment by LeeWannacott** [comment]
I will have a `Go` at this. I have been looking for an excuse to learn more Go and how releases work on GitHub anyway.

**Comment by strager** [comment]
Any progress on this, doge?

**Comment by pileofneurons** [comment]
Can I work on this?

**Comment by LeeWannacott** [comment]
This issue is being worked on: https://github.com/quick-lint/quick-lint-js/pull/669

**Comment by LeeWannacott** [comment]
Landed in: https://github.com/quick-lint/quick-lint-js/pull/669 :eyes:

**Comment by strager** [comment]
Issue #469 fixed in #669 with a hotfix in #966 😅
