### ISSUE TITLE
Website: improve security

### ISSUE THREAD

**Issue by strager** [quick-lint/quick-lint-js#477]
- [ ] HSTS
- [ ] Content Security policy
- [ ] Referrer policy
- [ ] X-Content-Type-Options ?
- [ ] X-Frame-Options ?
- [ ] X-XSS-Protection ?

https://observatory.mozilla.org/analyze/quick-lint-js.com

**Comment by strager** [comment]
I think beginners might be able to help with this task. I think most of these rules would be implemented using .htaccess files. (Perhaps I should write some documentation explaining how the site is deployed, so people can reproduce the deployment locally.)

**Comment by k1ng440** [comment]
i claim this issue

**Comment by strager** [comment]
I deployed the .htaccess change, but the headers don't seem to apply.

**Comment by strager** [comment]
> I deployed the .htaccess change, but the headers don't seem to apply.

This was my fault. I fixed it in commit a2540d28ff7d0a3a98ce378f74d8ad66821c7dee.

**Comment by strager** [comment]
We upgraded from F to B+: https://observatory.mozilla.org/analyze/quick-lint-js.com

Looks like we have some work to do with CSP. Here are the failing checks:

* Blocks execution of inline JavaScript by not allowing 'unsafe-inline' inside script-src 	
* Blocks execution of JavaScript's eval() function by not allowing 'unsafe-eval' inside script-src 	
* Blocks inline styles by not allowing 'unsafe-inline' inside style-src 	
* Clickjacking protection, using frame-ancestors 	
* Deny by default, using default-src 'none' 	
* Restricts use of the \<base\> tag by using base-uri 'none', base-uri 'self', or specific origins 	
* Restricts where \<form\> contents may be submitted by using form-action 'none', form-action 'self', or specific URIs

**Comment by strager** [comment]
@k1ng440 Do you think these issues are worth fixing?
