### ISSUE TITLE
5$: Website: <link rel=canonical>

### ISSUE THREAD

**Issue by strager** [quick-lint/quick-lint-js#481]

**Comment by strager** [comment]
I think we can slip `<link rel=canonical ...>` in website/public/common-head.ejs.html.

**Comment by wojito** [comment]
I claim this for-hire task. I expect payment after I complete this task. I will email the quick-lint-js team if I am assigned this task.

**Comment by Youness-Asserare** [comment]
I claim this for-hire task. I expect payment after I complete this task. I will email the quick-lint-js team if I am assigned this task.

**Comment by Youness-Asserare** [comment]
I would like to thank you for your twitch streams, I learned a lot and am
still learning !
This is my second contribution ever and can't wait to make more.
I would like you to hold onto my earnings for sending later.

Much appreciated
