### ISSUE TITLE
Link to error doc URLs

### ISSUE THREAD

**Issue by strager** [quick-lint/quick-lint-js#506]
e.g. https://quick-lint-js.com/errors/E074/

We would redirect `/errors/E074/` to `/errors/#E074`. Link to the non-fragment version just in case we refactor the website.

- [ ] LSP server
- [ ] CLI
- [ ] VS Code extension

**Comment by ahmafi** [comment]
For CLI links we need something like this?

![image](https://user-images.githubusercontent.com/12560109/142930406-8363d091-f4be-448c-b3dc-2a166a8a7132.png)

**Comment by strager** [comment]
> For CLI links we need something like this?

Nah, more like this:

<img width="984" alt="Screen Shot 2021-11-22 at 12 47 41 PM" src="https://user-images.githubusercontent.com/48666/142933099-4d3a07b1-3170-437d-99f4-002cdc5ecf46.png">
<img width="980" alt="Screen Shot 2021-11-22 at 12 47 49 PM" src="https://user-images.githubusercontent.com/48666/142933102-fb0efe71-f9b0-465f-9730-2b8b9001ed2a.png">

```sh
#!/bin/sh
printf 'hello.js:4:8: error: missing operand for operator [\e]8;;https://quick-lint-js.com/errors/#E0026\e\\E0026\e]8;;\e\\]\n'
```
https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda
