### ISSUE TITLE
5$: Website: remove empty <script> nodes

### ISSUE THREAD

**Issue by strager** [quick-lint/quick-lint-js#514]
We write empty `<script>` nodes in a few places to get Prettier to format server-side JavaScript code in our .ejs.html files. We shouldn't serve the empty `<script>` nodes to clients. Let's strip them from the HTML.

**Comment by krzysztof-grzybek** [comment]
I checked that, and it seems that `prettier` doesn't format javascript in `script` tags while running `yarn fmt`. So what's the requirement for this task?

**Comment by strager** [comment]
> So what's the requirement for this task?

Either:

* Remove `<script>` in the source code (by teaching Prettier about EJS, or finding another workaround), or
* Remove `<script> // </script>` from the generated HTML (by post-processing).

**Comment by Dreams-Happen** [comment]
Is https://github.com/quick-lint/quick-lint-js/blob/95795c6f808fdb8a7c13144db4cf8759fa54046b/website/public/common-nav.ejs.html the only file that has this empty <script>? This seems to be the only .ejs.html file which has one, unless I'm missing something.

**Comment by strager** [comment]
@Dreams-Happen No. Server-only `<script>`s are on many other pages, such as common-footer-nav.ejs.html and blog/syntax-errors-2021/index.ejs.html.

**Comment by strager** [comment]
Done in #717 (commit 9856993fae9809913f121c60b95f5f1c102b43e9).
