### ISSUE TITLE
"illegal instruction" crash

### ISSUE THREAD

**Issue by Frank-Buss** [quick-lint/quick-lint-js#53]
This code:
```
let i = "test
";
```
results in this output on my system:
```
/home/frank/tmp/test.js:1:9: error: unclosed string literal
/home/frank/tmp/test.js:2:1: error: unclosed string literal
../src/parse.cpp:563: fatal: token not implemented in parse_expression_remainder: string on line 2 column 1
Illegal instruction
```
Looks like the program crashed with an "illegal instruction".

**Comment by strager** [comment]
I think fixing the crash is a matter of telling `parse_expression_remainder` to stop parsing when it sees a string literal (instead of an operator).

Producing good error messages is another matter; we can punt on that for now.

**Comment by strager** [comment]
As of commit b9e4851, the code is parsing without a crash:
```
hello.js:1:9: error: unclosed string literal [E040]
```
