### ISSUE TITLE
Neovim - nvim-lspconfig update breaks quick-lint-js plugin

### ISSUE THREAD

**Issue by KasonBraley** [quick-lint/quick-lint-js#543]
Latest update to [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig) seems to have broken quick-lint-js.

#### Neovim Error Message
```
[lspconfig] Cannot access configuration for quick_lint_js. Ensure this server is listed in `server_configurations.md` or added
as a custom server.
```

### The issue appears to come from this breaking change: https://github.com/neovim/nvim-lspconfig/pull/1479

Looks like it might be a simple fix: https://github.com/jose-elias-alvarez/null-ls.nvim/issues/378#issuecomment-980076774 in this file: https://github.com/quick-lint/quick-lint-js/blob/be6302e4d535800bdcc2372b4005c146098d402c/plugin/vim/quick-lint-js.vim/lua/lspconfig/quick_lint_js.lua#L9

**Comment by KasonBraley** [comment]
Possibly related: https://github.com/neovim/nvim-lspconfig/issues/1075#issuecomment-980801779

**Comment by strager** [comment]
Asked for a solution: https://github.com/neovim/nvim-lspconfig/pull/1479#issuecomment-985217343

**Comment by mjlbach** [comment]
Where is the lspconfig configuration documented? I'm going to add a quick-lint configuration direct to lspconfig, so the documentation can be updated.

**Comment by KasonBraley** [comment]
> Where is the lspconfig configuration documented? I'm going to add a quick-lint configuration direct to lspconfig, so the documentation can be updated.

I believe it is here: https://github.com/quick-lint/quick-lint-js/blob/master/plugin/vim/quick-lint-js.vim/lua/lspconfig/quick_lint_js.lua

**Comment by KasonBraley** [comment]
@strager Current issue with the addition of quick-lint-js to `nvim-lspconfig` documented here: [https://github.com/neovim/nvim-lspconfig/pull/1533#issuecomment-986092573](https://github.com/neovim/nvim-lspconfig/pull/1533#issuecomment-986092573)

**Comment by mjlbach** [comment]
The default configuration in lspconfig should *just work* now.

**Comment by KasonBraley** [comment]
quick-lint-js can now be installed from `nvim-lspconfig` by following the [instructions](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#quick_lint_js). As per their [docs](https://github.com/neovim/nvim-lspconfig#install), Neovim 0.6 or Nightly is required for this to work.

**Comment by strager** [comment]
Fixed in commit b05ad7b8ab6c86512e904a2d6b899f7e81d74614.

I think quick-lint-js' plugin overrides nvim-lspconfig's built-in config, but I didn't test.

**Comment by mjlbach** [comment]
I would suggest removing the config in this plugin and relying on the one in lspconfig (users also likely want to call `setup{}` themselves.

**Comment by strager** [comment]
> I would suggest removing the config in this plugin and relying on the one in lspconfig

Why?
