### ISSUE TITLE
`:help quick-lint-js` doesn't work on Zbrow's Ubuntu 20.04 machine

### ISSUE THREAD

**Issue by strager** [quick-lint/quick-lint-js#545]

**Comment by Zeebrow** [comment]
Same results from within a `unbuntu:20.04` container.

Also, the `Zbrow's Ubuntu` distro has not been released yet. :P

**Comment by Zeebrow** [comment]
Might be a different dependency issue I just found.

Borrowing a duck computer (read not mine!!), I went to install qljs by following instructions here: https://github.com/quick-lint/quick-lint-js/tree/master/dist/debian

Commands and error output

[https://gist.github.com/Zeebrow/b333dedfb70f793ad3cced9669af9617](command history)
[https://gist.github.com/Zeebrow/b700d73b0c99ad530e3ea33dd2f5b89a](Output of sudo dpkg -i commands)

**Comment by strager** [comment]
Fixed in commit d1566cf6a8940870bcb14a001c2120cd69aac38f. (We forgot to ship the docs. Oops!)
