### ISSUE TITLE
12$: VS Code: hard to hover mouse over certain errors

### ISSUE THREAD

**Issue by strager** [quick-lint/quick-lint-js#554]
Example:
```js
console.log("hello") console.log("world")
```

VS Code shows a squiggly:
<img width="927" alt="Screen Shot 2021-12-02 at 1 18 52 PM" src="https://user-images.githubusercontent.com/48666/144504663-56137af8-1bf1-4d46-88c4-0e6f47d162ac.png">

but hovering the mouse cursor over the squiggly shows nothing.

The following example works as expected though:
```js
if (true)
```

**Comment by strager** [comment]
Workaround: first put the text cursor left of the squiggly, then move the mouse cursor over the text cursor:
<img width="1534" alt="Screen Shot 2021-12-02 at 1 17 10 PM" src="https://user-images.githubusercontent.com/48666/144504863-6d61c87e-7ccb-4cae-b2ca-d52349a86d05.png">

**Comment by strager** [comment]
This is probably a bug in VS Code.

**Comment by ahmafi** [comment]
Just mentioning that the same issue happens on the website.

**Comment by ahmafi** [comment]
Opened this [issue](https://github.com/microsoft/vscode/issues/138372) on VSCode to make sure that if it's a bug on their side.

**Comment by ahmafi** [comment]
They fixed it on VSCode and I have tested it with quick-lint-js.

https://github.com/microsoft/vscode/issues/136711

**Comment by strager** [comment]
Confirmed fixed in Visual Studio Code version 1.63.2 on macOS.
