### ISSUE TITLE
Improve error recovery for unterminated string literals

### ISSUE THREAD

**Issue by strager** [quick-lint/quick-lint-js#56]
Inspired by issue #53.

In the following code, the programmer probably intends to escape the newline with a backslash or use a template literal:

```javascript
let x = "hello
world";
```

Currently, quick-lint-js will interpret this code as having the following tokens:

1. `kw_let`
2. `identifier` (`x`)
3. `equal`
4. `string` (`"hello`)
5. `identifier` (`world`)
6. `string` (`";`)

Ideally, instead, it'd interpret this code as having the following tokens:

1. `kw_let`
2. `identifier` (`x`)
3. `equal`
4. `string` (`"helloworld"`)
5. `semicolon`

We can't just munch until the next `"`, 'cus that would be poor error recovery for code like this:

```javascript
console.log("starting se
startServer(port);
```

Idea: if we see an end-of-line when parsing a string literal, check the following line. If the following line has exactly one matching `"` or `'`, treat that matching quote as the end of the current string. Otherwise, treat the end-of-line as the end of the current string.

The code for string literal parsing is in lex.cpp, and the existing tests are in test-lex.cpp.

**Comment by A-thanasios** [comment]
Looking at this. Since the lexer only parses `\r` and `\n` as line terminators, the `\r\n` terminator is making the fix a bit uglier. One work around to this would be to parse all consecutive `\n` characters after the first `\r` or `\n` in a string literal. Is that fine?

**Comment by strager** [comment]
> Since the lexer only parses `\r` and `\n` as line terminators, the `\r\n` terminator is making the fix a bit uglier.

I don't know what would be uglier about handling CRLF (`\r\n`). Can you show some code?

Code exists in locator::cache_offsets_of_lines (src/location.cpp) to parse CRLF. I'm a bit surprised we don't already have anything in lexer to deal with CRLF.

> One work around to this would be to parse all consecutive \n characters after the first \r or \n in a string literal. Is that fine?

Wouldn't that make the following code lex differently depending on whether CRLF (`\r\n`) or LF (`\n`) is used for terminating lines?

```javascript
let x = "hello


world";
```

**Comment by A-thanasios** [comment]
> I don't know what would be uglier about handling CRLF (`\r\n`). Can you show some code?
> 
> Code exists in locator::cache_offsets_of_lines (src/location.cpp) to parse CRLF. I'm a bit surprised we don't already have anything in lexer to deal with CRLF. I guess we haven't needed it yet.
> 

I will follow that example to add CRLF parsing to the lexer.

> Wouldn't that make the following code lex differently depending on whether CRLF (`\r\n`) or LF (`\n`) is used for terminating lines?
> 
> ```js
> let x = "hello
> 
> 
> world";
> ```

Woops, you're right. I didn't think it through far enough.

**Comment by strager** [comment]
Looks like this is working well in commit b879f5138.
