### ISSUE TITLE
Mark JSX as supported in Deno

### ISSUE THREAD

**Issue by bartlomieju** [quick-lint/quick-lint-js#570]
Currently features table on the https://quick-lint-js.com/ is showing Deno as lacking support for JSX, however Deno's linter and LSP both support linting JSX and TSX:
<img width="465" alt="Screenshot 2021-12-08 at 20 40 58" src="https://user-images.githubusercontent.com/13602871/145273527-e7ff28e0-3489-45c7-b40a-e3e89e23d6d9.png">

```
deno lint components/interfaces.tsx components/interfaces.jsx util.ts
(no-empty) Empty block statement
if (c) {}
       ^^
    at /dev/docland/components/interfaces.jsx:14:7

    hint: Add code or comment to the empty block
    help: for further information visit https://lint.deno.land/#no-empty

(no-unused-vars) `foobar` is never used
function foobar() {
         ^^^^^^
    at /dev/docland/util.ts:11:9

    hint: If this is intentional, prefix it with an underscore like `_foobar`
    help: for further information visit https://lint.deno.land/#no-unused-vars

(ban-types) The corresponding lower-case primitive should be used
let c: String;
       ^^^^^^
    at /dev/docland/components/interfaces.tsx:23:7

    hint: Use `string` instead
    help: for further information visit https://lint.deno.land/#ban-types

(no-empty) Empty block statement
if (c) {}
       ^^
    at /dev/docland/components/interfaces.tsx:28:7

    hint: Add code or comment to the empty block
    help: for further information visit https://lint.deno.land/#no-empty

Found 4 problems
Checked 3 files

```

I would appreciate if that box could be ticked off ✅ thanks!

**Comment by strager** [comment]
I tested with an earlier version of Deno and I couldn't get JSX checking working in VS Code. I'll test with the latest version.

**Comment by strager** [comment]
Seems to work with various Deno versions (1.9.0, 1.14.1, 1.15.3, 1.16.4). I wonder why I couldn't get it working before.

I deployed commit 39b118db337890d6b7a63580f8e8d31db2e55e0c which fixed the comparison table.

Thanks for bringing the issue to my attention! Have a gluten-free cookie: :cookie:
