### ISSUE TITLE
8$: Warn when comma operator used in 'if' or 'while' or 'for' condition

### ISSUE THREAD

**Issue by strager** [quick-lint/quick-lint-js#585]
e.g. https://old.reddit.com/r/learnprogramming/comments/rh3ez8/continue_in_nested_while_loop_problem_javascript/

**Comment by yunusey** [comment]
Hi @strager, I found this issue to be related to the one I was working on for last couple of days (#939). I have also included switch conditions, but please let me know if you don't want them included. Thanks!
