### ISSUE TITLE
Run CI on pull requests

### ISSUE THREAD

**Issue by strager** [quick-lint/quick-lint-js#59]
The GitHub Actions workflows for building and testing only run on my branches, not on pull requests. Make them run on pull requests, too.

Previous attempt: https://github.com/strager/quick-lint-js/commit/e55b699d22a74140a31f9e9896657dc71ec0a391

**Comment by erlliam** [comment]
I'll give this a shot

**Comment by strager** [comment]
Landed as commit cadbfbb1db664e1016a76e7cc9b2ffcc55243e6f.
