### ISSUE TITLE
Interesting Pointing System for failures in the blog post

### ISSUE THREAD

**Issue by neunmalelf** [quick-lint/quick-lint-js#592]
[JavaScript syntax errors compared (2021)](https://quick-lint-js.com/blog/syntax-errors-2021/)

> 1/5: Ba, JSC, qljs, SM, and TS suggested incorrect solutions to the problem.

These tools get 1 Point for failing?

**Comment by strager** [comment]
> These tools get 1 Point for failing?

Yes. According to the rating scale:

> 1. The message suggests an incorrect solution or misleads the user, or there is no message reported at all.

Do you think 1/5 is inappropriate?

**Comment by strager** [comment]
The exact point amounts don't matter. What matters is how tools relate to each other.

A 1-5 scale is equivalent to a 0-4 scale. So you can pretend that 1/5 is actually 0/4.

> Don't give people ammunition for a debate.

There is no point system which will make everyone happy. It's inherently subjective.
