### ISSUE TITLE
Add eslint ruleset support

### ISSUE THREAD

**Issue by Viperwow** [quick-lint/quick-lint-js#596]
I think that most people on `eslint` have lots of the rulesets in the `.eslintrc` and want to use this rules just on top of the fast tool like `quick-lint-js`. It might help migrate people to your solution without complex reconfiguring.

**Comment by strager** [comment]
One major issue with ESLint's config files is that there are many file formats, including JavaScript. I don't want quick-lint-js to depend on a JavaScript engine, especially not to just load a config file.

Currently, the only overlapping options are predefined/global variables. I don't know if this is enough to justify supporting ESLint configs yet. (In the future there might be more overlap though.)

> It might help migrate people to your solution without complex reconfiguring.

You gave me an idea: a tool to convert ESLint configs into quick-lint-js configs. Do you think this would work?

**Comment by Viperwow** [comment]
Unfortunately, I don't know how it's going under the hood, but there is a standardized way of making ESLint plugins.
I think it would be quite complex doing such a tool

**Comment by strager** [comment]
Hmm, I think I misread your original message. I thought you were talking about the config file. But I think you meant something else.

Are you asking for most or all of ESLint's features in quick-lint-js? That sounds like a rewrite of ESLint. I don't know what to do with this very general task.

> there is a standardized way of making ESLint plugins.

If quick-lint-js was modified to support ESLint plugins as-is, then quick-lint-js will be about as slow as ESLint. Much of ESLint's slowness is in its rules. For example, I ran ESLint's CLI on a 663-line file with `TIMINGS=1` and got the following report:
```
Rule                              | Time (ms) | Relative
:---------------------------------|----------:|--------:
indent                            |    27.701 |    28.6%
import/no-unresolved              |     7.182 |     7.4%
import/no-extraneous-dependencies |     5.326 |     5.5%
import/order                      |     4.009 |     4.1%
import/no-self-import             |     3.693 |     3.8%
space-infix-ops                   |     2.180 |     2.3%
no-var                            |     1.433 |     1.5%
import/extensions                 |     1.377 |     1.4%
keyword-spacing                   |     1.328 |     1.4%
import/no-useless-path-segments   |     1.301 |     1.3%
```
quick-lint-js on the same machine with the same file takes about 4 milliseconds (but of course, quick-lint-js does less work).

---

I'm happy to discuss specific features which you want. You are welcome to request specific lint rules. But what you're asking here is not going to give you the speed improvements you're expecting.

You might be interested in [RSLint](https://rslint.org/). That tool is designed to be (roughly) similar to ESLint. But your ESLint rules would need to be rewritten to work with RSLint. (This is an easier task than making most ESLint rules work with quick-lint-js though!)

**Comment by Viperwow** [comment]
Ah, okay, I'll check this tool, thanks!

I understand your concern about the speed and agree with you.

But do the `quick-lint-js` support plugin making or there are any other plans to rely on the help of the community to implement missing rules?

**Comment by strager** [comment]
> But do the `quick-lint-js` support plugin making

[No, not yet.](https://github.com/quick-lint/quick-lint-js/blob/d3b80b2942d9ac696e666d872dbc1227a8f7d81a/docs/architecture/ADR014-Plugins.md)

> there are any other plans to rely on the help of the community to implement missing rules?

Not right now. All of quick-lint-js' rules so far are special. I need to implement some more rules to get a feel for how rules are usually structured. I think this will not happen soon.

**Comment by coderaiser** [comment]
Plugins can be slow, but if you choose a way of using [DSL for Abstract Syntax Trees](https://rust-analyzer.github.io/blog/2020/10/24/introducing-ungrammar.html) you can have a way to support plugins in json format:

```json
{
    "replace": {
        "var __a = __b": "const __a = __b"
    }
}
```

This is example of one of plugin types supported by 🐊[`Putout`](https://github.com/coderaiser/putout/tree/master/packages/engine-runner#replacer).

In this case all you need is to read and parse `JSON` everything else can be done in `C++` side :).

So you will get the most from two worlds: speed of low-level language and ability to write fast and simple extensions by the community of `JavaScript` developers.

**Comment by strager** [comment]
> if you choose a way of using [DSL for Abstract Syntax Trees](https://rust-analyzer.github.io/blog/2020/10/24/introducing-ungrammar.html) you can have a way to support plugins in json format

This is an interesting idea. I need to research this approach and see if it'll work with the plugins people use in ESLint and want in quick-lint-js.

**Comment by strager** [comment]
I think we might be able to add quick-lint-js rules to ESLint (#682), but I don't think we'll be able to add ESLint rules to quick-lint-js. (We could certainly write our own rules in quick-lint-js, but we can't reuse ESLint's code in quick-lint-js.) So I am going to close this task.

A pattern matching framework for lint rules (suggested by @coderaiser) sounds like a different path, so I filed a separate task for it: #692
