### ISSUE TITLE
Improve search engine SEO

### ISSUE THREAD

**Issue by strager** [quick-lint/quick-lint-js#598]

**Comment by strager** [comment]
Lots of people search "js lint". We could emphasize editor integration or easiness to stand out from JSLint ('code quality and coverage') and ESLint ('pluggable and configurable').

**Comment by strager** [comment]
We could try ranking better for "js lsp" and "javascript lsp".

https://github.com/prabirshrestha/vim-lsp/wiki/Servers-JavaScript
https://langserver.org/
https://microsoft.github.io/language-server-protocol/implementors/servers/

**Comment by strager** [comment]
#581 and #576 could help too.

**Comment by fabform** [comment]
Handy alternative list of [alternative search engines](https://fabform.io/a/alternative-search-engines)

**Comment by strager** [comment]
#625 would also help.

**Comment by strager** [comment]
#626 would also help.

**Comment by strager** [comment]
I created separate tasks for specific issues. There's no point in having a general issue like this one.
