### ISSUE TITLE
Refactor parser::parse_arrow_function_body_impl

### ISSUE THREAD

**Issue by strager** [quick-lint/quick-lint-js#638]
* Combine `expression::arrow_function_with_expression` and `expression::arrow_function_with_statement` into one class.
* Deduplicate parameter parsing.
* Refactor parameter parsing to not require an `expression` object.

**Comment by jvnho** [comment]
Hey I'm looking for my first contribution, can I take this one?

**Comment by strager** [comment]
@jvnho Sure!

**Comment by jvnho** [comment]
Hey @strager I wanted to let you know I wouldn't be able to complete this task, thanks for the opportunity anyway ! :))

**Comment by Rebraws** [comment]
Hi, I'm looking to make my first contribution to open source, can I work on this issue?

**Comment by strager** [comment]
> Hi, I'm looking to make my first contribution to open source, can I work on this issue?

Yes, you may.
