### ISSUE TITLE
Support wchar_t in command-line parsing

### ISSUE THREAD

**Issue by strager** [quick-lint/quick-lint-js#65]
The command-line parser uses `char`. This is [likely] problematic on Windows if command-line arguments contain non-ASCII characters. Make the command-line parser support `wchar_t` and `WinMain`.

This change might have ripple effects, such as the `CreateFileA` call in `read_file`. We should probably do some UTF-16-to-UTF-8 conversions to ease the transition.

**Comment by erlliam** [comment]
I am interested.

**Comment by strager** [comment]
Implemented in commit 9558fdd71718f4ef65434c971155a74bcbfa5862. Thanks, @erlliam.
