### ISSUE TITLE
Article: ESLint vs quick-lint-js

### ISSUE THREAD

**Issue by strager** [quick-lint/quick-lint-js#651]

**Comment by flowstate247** [comment]
It would be nice to have an ESLint+Unicorn vs Quick-lint-js+Prettier feature rules comparison.

It would help me better understand how complete the 200+ rules of Quick-lint-js are against the established competitor.

**Comment by strager** [comment]
> It would help me better understand how complete the 200+ rules of Quick-lint-js are against the established competitor.

Yeah, this makes sense.

TL;DR quick-lint-js is focused on correctness bugs and the editor experience. ESLint covers both style and bug finding and customization, and Unicorn focuses on style and modernization.

**Comment by strager** [comment]
This is basically a duplicate of #879.
