### ISSUE TITLE
add comma dangle support

### ISSUE THREAD

**Issue by ecstrema** [quick-lint/quick-lint-js#661]
I use eslint (mostly) for two rules: missing trailing comma and missing semi colon.

The second is already supported. I couldn't find info for the first. Is it supported too?

**Comment by strager** [comment]
quick-lint-js does not complain about valid code (such as a missing trailing comma, which is optional). It's currently designed to catch bugs, not style issues.

Is there a reason you want to use quick-lint-js instead of ESLint for style checking?

**Comment by Marr11317** [comment]
Well missing semi-colons are also optionals.

I am somewhat ashamed by how much things aren't faster even if our devices are. That's my reason to use quick-lint-js

**Comment by strager** [comment]
> Well missing semi-colons are also optional.

quick-lint-js does not report errors for optional semicolons, only required semicolons.

**Comment by strager** [comment]
Unfortunately, quick-lint-js won't implement style checking in the foreseeable future. So I'm marking this request as a won't-implement.
