### ISSUE TITLE
Add quick-lint-js to the Pop!_Shop for Pop!_OS

### ISSUE THREAD

**Issue by LeeWannacott** [quick-lint/quick-lint-js#670]
![image](https://user-images.githubusercontent.com/49783296/158926622-bbe23ffa-b977-4a7d-bac9-48cca754cb6f.png)
quick-lint-js doesn't exist on the Pop!_Shop :crying_cat_face:.

**Comment by strager** [comment]
Are other command-line programs in the Pop!_Shop? Is Pop!_Shop only available from Pop!_OS?

**Comment by LeeWannacott** [comment]
>  Is Pop!_Shop only available from Pop!_OS?

GitHub (with instructions to build): https://github.com/pop-os/shop 

You can build it on other distributions might not be headache free though (conflicting comments..):
https://www.reddit.com/r/linux4noobs/comments/mmwz2o/can_you_install_elementary_oss_app_center_or_pop/

> Are other command-line programs in the Pop!_Shop?

Yup; I can run cmatrix from terminal by installing it from the Pop!_Shop you can install some packages as (deb) or (flatpack).

![image](https://user-images.githubusercontent.com/49783296/158954031-7fb3e2c2-bb2a-42c2-b01c-88945738001f.png)
![image](https://user-images.githubusercontent.com/49783296/158953982-d9c20c13-6d53-4eb3-84be-d070ff0c8149.png)

**Comment by strager** [comment]
I think this is what we need to do:

1. Create an [AppStream metadata file](https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html).
2. In the Debian package, install the AppStream metadata file to [/usr/share/metainfo/](https://wiki.debian.org/AppStream/Guidelines).
3. Use the [appstream-generator tool](https://github.com/ximion/appstream-generator) to create the dep11 directory in our apt repo.

Other useful info:
* [Debian's AppStream docs](https://wiki.debian.org/AppStream)
* [Outdated DEP-11 docs](https://wiki.debian.org/DEP-11)
* [Example dep11 directory in apt repository](http://us.archive.ubuntu.com/ubuntu/dists/impish/main/dep11/)
* [Pop!_OS extra AppStream meta files](https://github.com/pop-os/appstream-data)
* `apt update` runs `appstreamcli refresh-cache`

**Comment by strager** [comment]
Commit ac9eb8ea0d5c0389b33000ad8dec64ffcb762ebe added the artwork and metadata to the Debian package, and updated our apt repository scripts. The next release (2.3.2 or 2.4.0 or 3.0.0) should list quick-lint-js in the Pop!_Shop, assuming the user has added our apt repository.

**Comment by strager** [comment]
I shipped version 2.4.0. Our apt repository should have the metadata necessary for the Pop!_Shop. @LeeWannacott Can you test for me?

**Comment by LeeWannacott** [comment]
![image](https://user-images.githubusercontent.com/49783296/163657295-21ab8970-aac4-4b80-9fd5-8bbc472911e6.png)
