### ISSUE TITLE
Build no-exception and no-RTTI variants on CI

### ISSUE THREAD

**Issue by strager** [quick-lint/quick-lint-js#68]
quick-lint-js should build with C++ exceptions and RTTI disabled. To make sure this remains true, add variants to CI which build quick-lint-js with these features disabled.

For GCC and Clang, I think the options we need are `-fno-exceptions` and `-fno-rtti`.

CI rules are inside the .github/ directory.

**Comment by omegahack0** [comment]
Would this apply to all env or any specific .yml or all of them?

**Comment by strager** [comment]
> Would this apply to all env or any specific .yml or all of them?

I think only to build-and-test.yml for now.

**Comment by strager** [comment]
We disable exceptions and RTTI by default now. So no need to test them explicitly in CI:

https://github.com/quick-lint/quick-lint-js/blob/a02e4513cae748772f5e7f8b67393c0247bb4d2a/cmake/QuickLintJSCompiler.cmake#L65-L77
