### ISSUE TITLE
Parse octal number literals

### ISSUE THREAD

**Issue by strager** [quick-lint/quick-lint-js#7]
quick-lint-js understands hexadecimal, binary, and decimal number literals, but doesn't understand octal number literals.

Teach quick-lint-js to parse octal number literals in lex.cpp and in test-lex.cpp.

**Comment by vegerot** [comment]
dibs

**Comment by vegerot** [comment]
strict and non-strict mode parse octal literals differently.  In non-strict mode `057`===`46`, but `058`===`58`.  In strict mode `058 throws a `SyntaxError`.

I'm not sure how we handle strict mode in quick-lint (but in chat you just told me we don't) it.  butt u also just sed in chat to allow the stupid format too (until we track strict mode).  so nvm
