### ISSUE TITLE
Fix CI warnings: "The `add-path` command is deprecated and will be disabled soon"

### ISSUE THREAD

**Issue by strager** [quick-lint/quick-lint-js#70]
The "build and test web demo" workflow is spewing warnings:

> The `add-path` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

Example run: https://github.com/quick-lint/quick-lint-js/actions/runs/305701526

Let's fix this warning.

**Comment by jgil-r** [comment]
Looking into this issue
