### ISSUE TITLE
Add --version option

### ISSUE THREAD

**Issue by strager** [quick-lint/quick-lint-js#71]
Add a `--version` option to the quick-lint-js command-line utility which prints quick-lint-js' version number and exits without linting.

Detect `--version` in options.cpp, add a variable to the `option` struct in options.cpp, test the option parsing in test-option.cpp, and print the version message in main.cpp.

See also the `--help` option introduced in PR #20.

**Comment by spicyyboi** [comment]
Hi, I'd like to be assigned to this issue!
