### ISSUE TITLE
8$: improve error for 'import {} from module;'

### ISSUE THREAD

**Issue by strager** [quick-lint/quick-lint-js#710]
`import {} from module;` is invalid because quotes are missing around the module name. qljs currently reports "E0054: unexpected token". Let's report something like "missing quotes around module name" instead.

**Comment by hanylovescode** [comment]
May I be assigned this issue?

**Comment by strager** [comment]
@hanylovescode No.

**Comment by hanylovescode** [comment]
I'm still going to try!

**Comment by hanylovescode** [comment]
Can you please point me to what files I should look at?

**Comment by strager** [comment]
test/test-parse-module.cpp, src/parse-statement.cpp, and src/quick-lint-js/diagnostic-types.h.

**Comment by AlexViaColl** [comment]
I have implemented this issue in #733
