### ISSUE TITLE
8$: TypeScript: warn on 'x! == y'

### ISSUE THREAD

**Issue by strager** [quick-lint/quick-lint-js#740]
`x! == y` is legal TypeScript but might have been a typo for `x !== y`. Issue a warning, suggesting parentheses around `x!` if a null assertion was intended.

**Comment by daethtech** [comment]
Hello,
As mentioned earlier in an email, I am able to take up this task to replace the other one I had, let me know if you need anything else in terms of assigning me to this task.
-G W
