### ISSUE TITLE
10$: Warn on 'x.toLowerCase() == "BANANA"'

### ISSUE THREAD

**Issue by strager** [quick-lint/quick-lint-js#741]
`String#toLowerCase()` (or any reasonable function named `toLowerCase` won't ever return characters in the range `/[A-Z]/`. Report a warning if the result of `toLowerCase` is compared with a string containing upper-case letters.

Similarly for `toUpperCase`.

I don't think we need to check that `x` has a string type.

**Comment by rol1510** [comment]
I claim this for-hire task. I expect payment after I complete this task. I will email the quick-lint-js team if I am assigned this task.

**Comment by rol1510** [comment]
Should it only check for functions which are exactly named `toLowerCase` or should it be case insensitive (`TOLOWERCASE`)?
Also, should it allow for pre- and post-fixes like `myToLowerCaseIsFaster`?
What about snake case `to_lower_case`?
