### ISSUE TITLE
Website: use HTTP/2

### ISSUE THREAD

**Issue by strager** [quick-lint/quick-lint-js#750]
Our website used to support HTTP/2, but now it doesn't seem to work. Let's enable it again.

**Comment by strager** [comment]
@k1ng440, you might be interested in this task. I think the issue is with mpm_prefork.

**Comment by k1ng440** [comment]
@strager i will take it

**Comment by k1ng440** [comment]
Sorry for the delay on this task. I will work on it later this week.

**Comment by k1ng440** [comment]
After doing some research I found out that `mpm_prefork` is not a good choice anymore and it does not work with HTTP/2 thus `mpm_event` should be used.

**Comment by k1ng440** [comment]
I have confirmed that HTTP/2 is working with `mpm_event`. do you want me to create a docker-compose to run those 2 containers?

**Comment by strager** [comment]
@k1ng440 Why do we need two containers? Can't we edit the existing image?

**Comment by k1ng440** [comment]
The best practice is to dedicate each container to running a single application because docker support only one `ENTRYPOINT` or  `CMD`. We can use `supervisord`, `runit` or something similar to accomplish it

**Comment by strager** [comment]
I'm confused. We only have a single top-level application: Apache httpd. httpd spawns PHP as needed, right? What other top-level program do we need to run explicitly in a container?

**Comment by k1ng440** [comment]
We have to switch to `php-fpm` because `npm_event` does not support mod_php like `npm_prefork` did. PHP-FPM is another process.

**Comment by strager** [comment]
I deployed @k1ng440's patch.
