### ISSUE TITLE
[typescript] Add friendly error message for `<T: type>()`

### ISSUE THREAD

**Issue by vegerot** [quick-lint/quick-lint-js#822]
Generic type constraints in TypeScript are defined with the `extends` keywords

```ts
function f<T extends string>(a: T) {}
```

However, sometimes people accidentally use `:` instead (being used to variable and parameter type annotations) like 

```ts
function f<T: string>(a: T) {}
```

Let's add a better error message for this case and suggest `extends` instead.
(p.s. there are other things besides `extends` but `extends` is the most likely)

**Comment by cmstoddard** [comment]
Please give this to me
