### ISSUE TITLE
[typescript] support variance annotations for type generics

### ISSUE THREAD

**Issue by vegerot** [quick-lint/quick-lint-js#824]
The [latest version of Typescript](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-7.html#optional-variance-annotations-for-type-parameters) supports [variance annotations](https://docs.scala-lang.org/tour/variances.html)

See this [Playground](https://www.typescriptlang.org/play?ts=4.8.0-beta#code/MYGwhgzhAEAyCWEAuAeeA7aAVAfNA3gL7QD0J0wA9gG5gBO8Y6S0AUEgJ4AOAptAAoNmPOikoBXFrmgBeaAAoAlLLxZS5KszphaDJklYYkIgGZhgfALKSwAIxA8EyNJglS8RddAy7GzNqwm4ujASPCUmCYu2DhKnmTe6LQg8AAm7Nx8-GKSMbLYXj5gKemcvNAAijnu+fLwAFzYyjKqhUnFaaxAA) for examples

```ts
class List<in T> {} // covariant 
type Printer<out T> = () => T // contravariant
interface MutableList<in out T> {} // invariant 

function f<in T>(){} // invalid
type P<out T> = T // invalid
type Q<out T> = (i: T) => T // invalid
```

**Comment by strager** [comment]
I don't know when this was implemented, but it's working in master (and probably version 2.15.0) now.
