### ISSUE TITLE
SSL certificate problem:https://c.quick-lint-js.com/releases/2.8.0/manual/linux.tar.gz

### ISSUE THREAD

**Issue by HUAHUAI23** [quick-lint/quick-lint-js#826]
https://c.quick-lint-js.com/releases/2.8.0/manual/linux.tar.gz
![image](https://user-images.githubusercontent.com/43649186/185633737-f7279683-ac44-4cb4-8ec9-7b67a42ad250.png)

**Comment by strager** [comment]
Thanks for letting me know! I'll investigate.

**Comment by strager** [comment]
Fixed by running the following commands on the server:
```
$ systemctl stop quick-lint-js-web-docker.service
$ certbot
3: c.quick-lint-js.com
$ systemctl start quick-lint-js-web-docker.service
```
