### ISSUE TITLE
Check Go version in tools/update-translator-sources

### ISSUE THREAD

**Issue by Rebraws** [quick-lint/quick-lint-js#833]
I wanted to test something with the quick-lint-js CLI tool, and I noticed that the script `tools/compile-translations.go` gives an error when using a version of Go lower than 1.16.

Error: `undefined: os.ReadDir`

I think it would be nice if instead of crashing, the script `tools/update-translator-sources` performed a version check and displayed a message like `Requires at least Go 1.16.` if the requirement isn't met.

Maybe it could be a good first issue for someone new to programming.

**Comment by strager** [comment]
Good idea. We should also check that gettext is installed (`xgettext` `msgmerge` commands). Or at least document all of this in docs/TRANSLATING.md.

**Comment by strager** [comment]
Implemented in commit 2d93a6726de32df9d062109b9f40b0ab5430ed91.
