### ISSUE TITLE
7$: warn on 'x == a || null' and 'x == a || undefined'

### ISSUE THREAD

**Issue by strager** [quick-lint/quick-lint-js#836]

**Comment by strager** [comment]
I think we can tweak our existing logic for [E0190](https://quick-lint-js.com/errors/E0190/).

**Comment by strager** [comment]
For this task, you can look at the logic for either:

* E0286/E0287 (`parser::error_on_pointless_string_compare` in `src/quick-lint-js/fe/parse.cpp`), introduced in commit 35207e6616267c6c81be63f47ce97ec2452d60df, or
* E0190 (`parser::error_on_sketchy_condition` in `src/quick-lint-js/fe/parse.cpp`), introduced in 1634b9808e0785ca75dbf4fb545a40ee403ebc51.

The logic and testing for this lint should be similar to the above lints.

Tests would go in test/test-parse-warning.cpp.

**Comment by rohitsasi720** [comment]
I can work on this issue

**Comment by strager** [comment]
@rohitsasi720 Do you need any help?

**Comment by HarshitAghera** [comment]
@strager , Can I take up this issue?

**Comment by strager** [comment]
@HarshitAghera I suggest finishing issue #852 first before working on this issue.

@rohitsasi720 Have you made progress on this task?

**Comment by HarshitAghera** [comment]
@strager, can I start working on this?

**Comment by strager** [comment]
@HarshitAghera Yes you may!
