### ISSUE TITLE
LSP: Language Server Protocol server

### ISSUE THREAD

**Issue by strager** [quick-lint/quick-lint-js#84]
- [x] Basic integration
- [x] Accurate location information (including UTF-16 quirkiness)
- [x] Incremental changesets
- [x] Protocol benchmarks
- [ ] Testing with LSP clients
  - [ ] Visual Studio Code
  - [ ] Vim: ALE
  - [ ] Vim: other plugins
  - [ ] Neovim
  - [ ] Emacs?
  - [ ] Sublime?

**Comment by vegerot** [comment]
My heart throbs for CoC.nvim support

**Comment by strager** [comment]
Commit 5f966910b implemented incremental changes.

**Comment by strager** [comment]
LSP support seems decent now (aside from parser crashes). I made separate tasks for the various plugins: #106, #105, #104, #103, #102.
