### ISSUE TITLE
[website] [SEO]: switch "easy setup" and "license" in "Features" table

### ISSUE THREAD

**Issue by vegerot** [quick-lint/quick-lint-js#841]
<img width="684" alt="image" src="https://user-images.githubusercontent.com/5297725/190717837-643c0051-12b4-4d3c-8f94-f8e4a859f2c2.png">

While many people care a lot about which license their linters use (like this linter's developer), when it comes to people just googling for a good tool, I think how much work it takes to get up and running is a faster selling point

**Comment by kptil** [comment]
Could I take this on? I'm working another good first issue as my first contrib that's a bit more complicated, and this would help me gain some confidence with your workflow and contributing guidelines. If I understand correctly this requires altering the order of the table rows in website/public/index.ejs.html.

**Comment by vegerot** [comment]
Well I won't stop you!  Good luck

**Comment by strager** [comment]
Google updated:
<img width="794" alt="Screen Shot 2022-09-22 at 1 26 02 PM" src="https://user-images.githubusercontent.com/48666/191844338-c34ca195-575b-49ca-abe2-cde8a9768248.png">
