### ISSUE TITLE
5$: better diagnostic on `async export`

### ISSUE THREAD

**Issue by vegerot** [quick-lint/quick-lint-js#842]
More broadly, better diagnostics on misordered function modifiers:

- `async export`
- `function async main()`

Expected:
- "You meant `export async`.  `export` modifier should go before `async` modifier"
- "You meant `async function main`.  `async` modifier should go before `function` keyword."

Actual:
- "error: unexpected token [E0054]"
- "error: unexpected token [E0054]"

**Comment by vegerot** [comment]
Is it worth saying this [happens every time](https://github.com/97-things/97-things-every-programmer-should-know/blob/master/en/thing_38/README.md#:~:text=how%20often%20this%20will%20make%20the%20bug%20appear.)? 😛

**Comment by strager** [comment]
Good ideas.

**Comment by vegerot** [comment]
If someone says `function async main()`, we **know** they meant `async function main()`, so why not tell them?

**Comment by vegerot** [comment]
It's not that the current diagnostic is _wrong_.  `main` _is_ an unexpected token; but we can provide a more specific diagnostic

**Comment by strager** [comment]
> async is not a reserved word and could be used as a function name. Even though it's not recommended "function async()" is valid and "main" would cause the error.

Correct. We can look at the token after `async` (the function's name). If it's an identifier, then report an error saying that `function` and `async` need to be swapped.

**Comment by AlekLefebvre** [comment]
https://github.com/quick-lint/quick-lint-js/pull/870

I'm new to this project, please let me know if there's anything I need to improve. Thank you!

**Comment by strager** [comment]
@AlekLefebvre implemented this in #870.
