### ISSUE TITLE
Check clang-format version in tools/format

### ISSUE THREAD

**Issue by Guilherme-Vasconcelos** [quick-lint/quick-lint-js#865]
Similar to https://github.com/quick-lint/quick-lint-js/issues/833, I think it would be nice if `tools/format` checked clang-format version

Currently it tries to use the version available in the system, but, as already explained in `CONTRIBUTING.md`, if your version is different than 9 your formatter's output will likely be different than CI's, in which case the pipeline can fail when you open the PR. We could have a warning to remember the developer about that.

**Comment by strager** [comment]
Good idea.
