### ISSUE TITLE
General Question about future of the project.

### ISSUE THREAD

**Issue by frank-dspeed** [quick-lint/quick-lint-js#875]
i saw you do a lot of tight coupling like

```
#include <cstddef>
#include <cstring>
#include <quick-lint-js/assert.h>
#include <quick-lint-js/container/string-view.h>
#include <quick-lint-js/lsp/lsp-uri.h>
#include <quick-lint-js/port/integer.h>
#include <string>
#include <string_view>
```

i am trying to identify a good entry point where i simply could send stuff into that i could most best build indipendent with cmake or gcc is there one or do you plan to handle this always as big app?

to be more clear i want to integrate that directly into engines that means i expose a JS Object for the cpp code 

```js
qiclint(/** @type {cstring} */ "string") comes into mind where can i drive that from 
```

**Comment by frank-dspeed** [comment]
i also looked into the plugin stuff as i tought that would be a natural fit maybe exposing a cpp api in plugins ? 

then i can depend on that? and u use the same API for your NAN or NodeJS Bindings? and so on? 

a generic plugin api? so that i get a relativ stable c abi out of that?

**Comment by frank-dspeed** [comment]
i guess this helps me to identify the files that are needed to add a rule and use it so i could drive the interface from that to add and remove rules: 

- [ ] https://github.com/quick-lint/quick-lint-js/pull/870/files

maybe it is the most easy to write a new code generator that reads the definitions from the /fe folder and then creates something modular out of that.

**Comment by frank-dspeed** [comment]
@strager i come to the final conclusion that i would want to ask you to define something like a IDL or Domain Specific Language to abstract the rule set like key value pairs ast condition = error code 

so that i can implement the rule set more easy and even adopt it also it would be great if we could make the benchmark cross lsp stack a big easyer.

i would love to compair against a special version of eslint that i use internal running on directly v8 at ring 0 epoll 

also i compiled eslint highly optimized directly into the engine. 

a less optimized public implementation of that concept is called just and ranks 1 at a reputable benchmark https://www.techempower.com/benchmarks/#section=data-r21&test=composite outperforming the most raw c and c++ frameworks.

are you interrested?

**Comment by frank-dspeed** [comment]
my motivation is i love consistent good expressiv error messages and working with you on that would be a plesure but i do not like your infrastructure. do not get me wrong it is awsome you recreated a lot of nice low level stuff but i would now love to take this to the next level. Your linter for example runs on a lot of environments already but we all know it would be most efficent.

when it runs directly inside the editor it self without LSP and that transport layers. i got no good error layer at present so this would be the chance.

my current alternative is typescript wich also got no good error set while the performance is good when staticly compiled.

**Comment by strager** [comment]
> i would want to ask you to define something like a IDL or Domain Specific Language to abstract the rule set like key value pairs ast condition = error code

This kind of feature sounds like a good idea for the future, but medium-term this is not the direction I want to take quick-lint-js in.

**Comment by strager** [comment]
> Your linter for example runs on a lot of environments already but we all know it would be most efficent.
>
> when it runs directly inside the editor it self without LSP and that transport layers.

I agree. This is why quick-lint-js' Visual Studio Code extension is a native extension, rather than being an LSP bridge. (VS Code's extension host is still out-of-process, but that's a VS Code architectural decision which I cannot change.)

I would rather make editor plugins tailored to each editor rather than a generic API which might be fast for some editors and slow for other editors.

**Comment by strager** [comment]
> my current alternative is typescript wich also got no good error set

From my limited experience with TypeScript, the TypeScript compiler catches tons of errors. What kind of errors do you wish the TypeScript compiler also caught?

**Comment by frank-dspeed** [comment]
@strager i have no exact roadmap i am working on a special effort to unifie the builds of a large amount of repos in the ecosystem all the core stuff needed to build webplatforms we want to create a shared universal base for electron, nodejs, webkit you name it. as also we want to implement a standard module system and ipc we finished that parts already.

v8 and chromium got now fully connected via MOJO::IPC this allows us to pass sharedMemory via atomics already.

At present i am improving the compiler toolchains internal so that we can fully compile our self with ECMAScript and the new C++ Module system the Module System is sexy we use Template Objects And Function

and then we reference that in ASM directly as binary we got sub ms compile times for a lot of stuff even if we compile static. 

it is as simple as
```Cpp
void NAMESPACE::Modules(const FunctionCallbackInfo<Value> &args) {
  Isolate *isolate = args.GetIsolate();
  Local<Context> context = isolate->GetCurrentContext();
  Local<Array> m = Array::New(isolate);
  int i = 0;
  for (auto const& module : modules) {
    m->Set(context, i++, String::NewFromUtf8(isolate, module.first.c_str(),
      NewStringType::kNormal, module.first.length()).ToLocalChecked()).Check();
  }
  args.GetReturnValue().Set(m);
}

// expose Modules in the new Isolate
SET_METHOD(isolate, target, "modules", Modules);

// binary integrate js
v8::builtins_add("lib/inspector.js", _binary_lib_inspector_js_start, _binary_lib_inspector_js_end - _binary_lib_inspector_js_start);

// Example Module C++
void just::vm::EnterContext(const FunctionCallbackInfo<Value> &args) {
  Local<Object> ab = args[0].As<Object>();
  v8_context* handle = (v8_context*)ab->GetAlignedPointerFromInternalField(1);
  handle->context.Get(args.GetIsolate())->Enter();
}
```

I think you get the idea this way we create a way to script able ultra fast REPL and ondemand build and integrate C then we spawn workers and link them via something that we call Capability based Protocol

what do you think about that maybe you would like to decouple your stuff wit the same patterns? i mean Wouldn't it be cool to build quicklint in JS/ECMAScript?  I saw you code a lot of stuff that v8 does for example thats why we took it as our core. We take it now even as ring 0 kernel layer that links drivers.

**Comment by frank-dspeed** [comment]
about the typescript compiler i will replace it as i will replace your when you do not adopt our new patterns but i want to join the error Messages your error messages are better and the others that are bad from typescript need a replacement

we do not need the LSP anymore we exposed directly binary protocols and interfaces that you can use and expose via cli flags and stdio pipe. With the new electron builds you will be able to spawn electron in a process and directly controllit via devtools and this way you can link your linter also without even using the extension interface. 

but sure you can also use that you can full access to the full electron internals same already true for browsers we already started some years before experimenting with that 

- https://github.com/GoogleChromeLabs/carlo

there is to much to write here but i know you will get the idea and i am not a imposter i know exactly what i am talking about even if my english is not the best :)

**Comment by frank-dspeed** [comment]
maybe you remember me i am the one who did want to code the wasm web browser and in fact i did that now we are also replacing Mesa3d EGL and call it a day 👍🏻 

Working now on AsteriskGL *GL The final graphics layer

**Comment by frank-dspeed** [comment]
## Update the C-API is Awsome
- I take that 👍🏻  i can maintain updates via codeMods thats not a problem we work with code generators and templates 
  - we get that even automatic updated no problem no human needed.
  
 Thanks for the good work will look into this from time to time would be nice if you could keep the c-api file name around so that i do not need to set some AI Tasks to guess the entrypoint again :). I also hate bisect

**Comment by strager** [comment]
> what do you think about that 

What you described seems unrelated to the purpose of quick-lint-js.

> i mean Wouldn't it be cool to build quicklint in JS/ECMAScript?

No, that doesn't sound interesting to me.

**Comment by frank-dspeed** [comment]
@strager i did closed that because i was assuming that already and it is total ok as long as you would do me the favor of suggesting over the long run to make it more easy to identify the meaningful of this project and that are the linting rules i do not care for anything else.

If you do not make that more easy it will also not block me it will shift the priority till codeMods's exist to automaticly throw that code into our KI Driven compiler which will extract all that on the raw Symbol Compiler feedback level this will delay adoption by only 3 years if you get it done to isolate the rules into a more indipendent component as FE (frontend) then this would speed up that process. 

Cheers and best wishes.
