### ISSUE TITLE
Website: demo broken with Grepper browser extension installed

### ISSUE THREAD

**Issue by strager** [quick-lint/quick-lint-js#886]
https://addons.mozilla.org/en-GB/firefox/addon/grepper/
https://quick-lint-js.com/demo/
https://cdn.discordapp.com/attachments/640652660839677964/1039647971777716244/image.png

**Comment by clegoz** [comment]
Same issue #719. I think, changes in e7c6c7951f8c44fa360401fc0ea876b295d5199b caused this again.

**Comment by strager** [comment]
Fixed in commit 9fafaa963a22d05f6ed9e833ccaf4dc131723a9f.
