### ISSUE TITLE
Add RSS feed for website blog?

### ISSUE THREAD

**Issue by Pat-Lafon** [quick-lint/quick-lint-js#904]
Hello! I was reading the blog post "https://quick-lint-js.com/blog/cpp-vs-rust-build-times/" from This Week in Rust and wanted to add the blog to my NetNewsWire list. However, using the above link/using "https://quick-lint-js.com/blog/" didn't work which I imagine because there isn't an RSS feed I can subscribe to?

Has there been consideration to adding an RSS feed? I'm not totally sure what's involved.

**Comment by strager** [comment]
An RSS feed is a great idea! I'll look into it.

**Comment by strager** [comment]
I added an RSS feed in commit f2a0718a28d819312be00d7e797a82014dc3e639.

@Pat-Lafon, can you please test? You should be able to access the RSS feed from the blog post. If not, let me know. (I don't know how people normally use RSS. I'm not an RSS user myself. I also don't have a device to try NetNewsWire on.)

**Comment by Pat-Lafon** [comment]
Works for me, thanks!

**Comment by strager** [comment]
You inspired me to make an RSS feed for the releases page too. Thanks! https://quick-lint-js.com/releases/
