### ISSUE TITLE
5$: update shell completions

### ISSUE THREAD

**Issue by strager** [quick-lint/quick-lint-js#918]
The `completions/` directory contains tab-completion scripts for various shells. They are out of date. They're missing `--language` and maybe other options (full list: https://quick-lint-js.com/cli/#_options). Update them, please!

**Comment by wilson1375** [comment]
Can i work on this?

**Comment by jakecastelli** [comment]
is there any update on this one @wilson1375? if not, would you mind me working on this? cheers

**Comment by jakecastelli** [comment]
Hi strager, I have a quick question in terms of updating the autocompletion helper text, should I reference the doc [here](https://quick-lint-js.com/cli/#_options)  or the main.cpp file?

e.g.
for the first one option in the doc `--output-format=format`, the doc says `Customize how errors are printed.` but the current autocomplete and main.cpp are saying: `Format to print feedback. (not exactly the same but quite similar)

**Comment by strager** [comment]
> should I reference the doc [here](https://quick-lint-js.com/cli/#_options) or the main.cpp file?

Use the documentation from the website (which can also be found in `docs/cli.adoc`).
