### ISSUE TITLE
26$: Parse {async=3, get=4, set=5} variable declarations

### ISSUE THREAD

**Issue by strager** [quick-lint/quick-lint-js#96]
The following code crashes when given to quick-lint-js:
```js
let {async=3, get=4, set=5} = {};
```
Error:
```
../src/parse.cpp:1299: fatal: token not implemented in parse_object_literal: equal on line 1 column 11
zsh: illegal hardware instruction  ./build/quick-lint-js hello.js
```

**Comment by strager** [comment]
I think we should rewrite the binding parser to not parse an expression.

**Comment by strager** [comment]
> I think we should rewrite the binding parser to not parse an expression.

I think this might be reused by the function parameter parser. Hopefully they have similar or identical rules.

**Comment by singalhimanshu** [comment]
I claim this for-hire task. I expect payment after I complete this task. I will email the quick-lint-js team if I am assigned this task.

**Comment by strager** [comment]
> I think we should rewrite the binding parser to not parse an expression.

Actually, this is a bad idea. How would we parse the following code otherwise:
```js
let f = ({k = true} = {}) => {};
```
