### ISSUE TITLE
8$: warn on 2^8, 10^2, etc.

### ISSUE THREAD

**Issue by strager** [quick-lint/quick-lint-js#997]
Inspiration: GCC's -Wxor-used-as-pow: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=90885

Instead of `2^8`, the user meant `2**8` instead.

We should be cautious about what we diagnose. Perhaps for now only diagnose with a base of `2` or `10` and a literal exponent?

**Comment by JiaYiChow** [comment]
@strager I would like to take up this issue as my first contribution to open source. I claim this for-hire task. I expect payment after I complete this task. I will email the quick-lint-js team if I am assigned this task.

**Comment by slayeh17** [comment]
Hi @JiaYiChow sorry if I sound rude but are you supposed to ask for payment so upfront ? This is an open source project after all.

**Comment by JiaYiChow** [comment]
Hi @slayeh17, this issue is labelled as 'for hire', the [docs](https://quick-lint-js.com/hiring/) clearly state that this issue is paid and to quote the exact same words as I did. If you looked around the other issues you find that other people are doing it as well

**Comment by slayeh17** [comment]
> Hi @slayeh17, this issue is labelled as 'for hire', the [docs](https://quick-lint-js.com/hiring/) clearly state that this issue is paid and to quote the exact same words as I did. If you looked around the other issues you find that other people are doing it as well

Oh I am sorry my bad😅, I was just a little surprised to see your comment.
