### ISSUE TITLE
Debian installation failed on docker ubuntu image

### ISSUE THREAD

**Issue by jakecastelli** [quick-lint/quick-lint-js#998]
The installation refers [here](https://quick-lint-js.com/install/cli/debian/).

Step to reproduce:

_note: `sudo` is not required because you are `root` user in the container._

1. `docker pull ubuntu`
2. `docker run -it ubuntu bash`
3. `apt-get update && apt-get install -y`
4. `apt-get install curl gnupg -y`
5. `curl https://c.quick-lint-js.com/quick-lint-js-release.key | apt-key add -`
6. `printf '\n# From: https://quick-lint-js.com/install/cli/debian/\ndeb [arch=amd64] https://c.quick-lint-js.com/debian experimental main\n' | tee /etc/apt/sources.list.d/quick-lint-js.list`
7. `apt-get update`
8. `apt-get install quick-lint-js`

Error:
```bash
root@eb179ef2e35f:/# apt-get install quick-lint-js
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package quick-lint-js is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'quick-lint-js' has no installation candidate
```

I am on M1 - MacOS 13.1

**Comment by strager** [comment]
The problem is that you are on aarch64, but our Debian repos only contains amd64 binaries.

I tested your instructions on an amd64 host and they worked fine. I tested on an aarch64 host and I got the same error as you.

The solution is for me to add aarch64 binaries to our Debian repos.

**Comment by strager** [comment]
I added ARM64 support in the infrastructure, but `apt install` will still fail until I make a new release.

**Comment by strager** [comment]
Releases starting at version 2.14.0 should have a Debian ARM64 build.
